package com.mjj.orm.mybatis.demo.dto;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_mmall_template
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TMmallTemplate extends BaseEntity {
    /**
     * Database Column Remarks:
     *   自增主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_template.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   收银台模板名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_template.template_name
     *
     * @mbg.generated
     */
    private String templateName;

    /**
     * Database Column Remarks:
     *   是否上线，0未上线 1上线
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_template.is_online
     *
     * @mbg.generated
     */
    private Byte isOnline;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_template.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     * Database Column Remarks:
     *   修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_template.modifier
     *
     * @mbg.generated
     */
    private String modifier;

    /**
     * Database Column Remarks:
     *   收银台模板创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_template.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   收银台模板修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_template.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * Database Column Remarks:
     *   收银台模板code
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_template.template_code
     *
     * @mbg.generated
     */
    private String templateCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_template.id
     *
     * @return the value of t_mmall_template.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_template.id
     *
     * @param id the value for t_mmall_template.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_template.template_name
     *
     * @return the value of t_mmall_template.template_name
     *
     * @mbg.generated
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_template.template_name
     *
     * @param templateName the value for t_mmall_template.template_name
     *
     * @mbg.generated
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_template.is_online
     *
     * @return the value of t_mmall_template.is_online
     *
     * @mbg.generated
     */
    public Byte getIsOnline() {
        return isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_template.is_online
     *
     * @param isOnline the value for t_mmall_template.is_online
     *
     * @mbg.generated
     */
    public void setIsOnline(Byte isOnline) {
        this.isOnline = isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_template.creator
     *
     * @return the value of t_mmall_template.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_template.creator
     *
     * @param creator the value for t_mmall_template.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_template.modifier
     *
     * @return the value of t_mmall_template.modifier
     *
     * @mbg.generated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_template.modifier
     *
     * @param modifier the value for t_mmall_template.modifier
     *
     * @mbg.generated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_template.create_time
     *
     * @return the value of t_mmall_template.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_template.create_time
     *
     * @param createTime the value for t_mmall_template.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_template.modify_time
     *
     * @return the value of t_mmall_template.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_template.modify_time
     *
     * @param modifyTime the value for t_mmall_template.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_template.template_code
     *
     * @return the value of t_mmall_template.template_code
     *
     * @mbg.generated
     */
    public String getTemplateCode() {
        return templateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_template.template_code
     *
     * @param templateCode the value for t_mmall_template.template_code
     *
     * @mbg.generated
     */
    public void setTemplateCode(String templateCode) {
        this.templateCode = templateCode;
    }
}