package com.mjj.orm.mybatis.demo.dto;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_mmall_order_refund
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TMmallOrderRefund extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund.order_no
     *
     * @mbg.generated
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund.pay_business_no
     *
     * @mbg.generated
     */
    private String payBusinessNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund.pay_order_id
     *
     * @mbg.generated
     */
    private String payOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund.refund_no
     *
     * @mbg.generated
     */
    private String refundNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund.refund_price
     *
     * @mbg.generated
     */
    private BigDecimal refundPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     * Database Column Remarks:
     *   订单状态 1:发起退款 8:退款成功 9:退款失败
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund.pay_refund_no
     *
     * @mbg.generated
     */
    private String payRefundNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund.pay_refund_channel_no
     *
     * @mbg.generated
     */
    private String payRefundChannelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund.pay_refund_time
     *
     * @mbg.generated
     */
    private Date payRefundTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund.id
     *
     * @return the value of t_mmall_order_refund.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund.id
     *
     * @param id the value for t_mmall_order_refund.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund.user_id
     *
     * @return the value of t_mmall_order_refund.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund.user_id
     *
     * @param userId the value for t_mmall_order_refund.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund.order_id
     *
     * @return the value of t_mmall_order_refund.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund.order_id
     *
     * @param orderId the value for t_mmall_order_refund.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund.order_no
     *
     * @return the value of t_mmall_order_refund.order_no
     *
     * @mbg.generated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund.order_no
     *
     * @param orderNo the value for t_mmall_order_refund.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund.pay_business_no
     *
     * @return the value of t_mmall_order_refund.pay_business_no
     *
     * @mbg.generated
     */
    public String getPayBusinessNo() {
        return payBusinessNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund.pay_business_no
     *
     * @param payBusinessNo the value for t_mmall_order_refund.pay_business_no
     *
     * @mbg.generated
     */
    public void setPayBusinessNo(String payBusinessNo) {
        this.payBusinessNo = payBusinessNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund.pay_order_id
     *
     * @return the value of t_mmall_order_refund.pay_order_id
     *
     * @mbg.generated
     */
    public String getPayOrderId() {
        return payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund.pay_order_id
     *
     * @param payOrderId the value for t_mmall_order_refund.pay_order_id
     *
     * @mbg.generated
     */
    public void setPayOrderId(String payOrderId) {
        this.payOrderId = payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund.refund_no
     *
     * @return the value of t_mmall_order_refund.refund_no
     *
     * @mbg.generated
     */
    public String getRefundNo() {
        return refundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund.refund_no
     *
     * @param refundNo the value for t_mmall_order_refund.refund_no
     *
     * @mbg.generated
     */
    public void setRefundNo(String refundNo) {
        this.refundNo = refundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund.refund_price
     *
     * @return the value of t_mmall_order_refund.refund_price
     *
     * @mbg.generated
     */
    public BigDecimal getRefundPrice() {
        return refundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund.refund_price
     *
     * @param refundPrice the value for t_mmall_order_refund.refund_price
     *
     * @mbg.generated
     */
    public void setRefundPrice(BigDecimal refundPrice) {
        this.refundPrice = refundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund.operator
     *
     * @return the value of t_mmall_order_refund.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund.operator
     *
     * @param operator the value for t_mmall_order_refund.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund.status
     *
     * @return the value of t_mmall_order_refund.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund.status
     *
     * @param status the value for t_mmall_order_refund.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund.pay_refund_no
     *
     * @return the value of t_mmall_order_refund.pay_refund_no
     *
     * @mbg.generated
     */
    public String getPayRefundNo() {
        return payRefundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund.pay_refund_no
     *
     * @param payRefundNo the value for t_mmall_order_refund.pay_refund_no
     *
     * @mbg.generated
     */
    public void setPayRefundNo(String payRefundNo) {
        this.payRefundNo = payRefundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund.pay_refund_channel_no
     *
     * @return the value of t_mmall_order_refund.pay_refund_channel_no
     *
     * @mbg.generated
     */
    public String getPayRefundChannelNo() {
        return payRefundChannelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund.pay_refund_channel_no
     *
     * @param payRefundChannelNo the value for t_mmall_order_refund.pay_refund_channel_no
     *
     * @mbg.generated
     */
    public void setPayRefundChannelNo(String payRefundChannelNo) {
        this.payRefundChannelNo = payRefundChannelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund.pay_refund_time
     *
     * @return the value of t_mmall_order_refund.pay_refund_time
     *
     * @mbg.generated
     */
    public Date getPayRefundTime() {
        return payRefundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund.pay_refund_time
     *
     * @param payRefundTime the value for t_mmall_order_refund.pay_refund_time
     *
     * @mbg.generated
     */
    public void setPayRefundTime(Date payRefundTime) {
        this.payRefundTime = payRefundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund.update_time
     *
     * @return the value of t_mmall_order_refund.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund.update_time
     *
     * @param updateTime the value for t_mmall_order_refund.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund.create_time
     *
     * @return the value of t_mmall_order_refund.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund.create_time
     *
     * @param createTime the value for t_mmall_order_refund.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund.reason
     *
     * @return the value of t_mmall_order_refund.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund.reason
     *
     * @param reason the value for t_mmall_order_refund.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason;
    }
}