package com.mjj.orm.mybatis.demo.dto;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_mmall_order_refund_notify
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TMmallOrderRefundNotify extends BaseEntity {
    /**
     * Database Column Remarks:
     *   自增ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund_notify.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund_notify.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   订单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund_notify.order_no
     *
     * @mbg.generated
     */
    private String orderNo;

    /**
     * Database Column Remarks:
     *   商家ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund_notify.vendor_id
     *
     * @mbg.generated
     */
    private Long vendorId;

    /**
     * Database Column Remarks:
     *   自动续费sku
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund_notify.bind_id
     *
     * @mbg.generated
     */
    private String bindId;

    /**
     * Database Column Remarks:
     *   通知状态     1: 成功    2: 失败     3: 放弃通知
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund_notify.notify_status
     *
     * @mbg.generated
     */
    private Byte notifyStatus;

    /**
     * Database Column Remarks:
     *   通知次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund_notify.notify_cnt
     *
     * @mbg.generated
     */
    private Integer notifyCnt;

    /**
     * Database Column Remarks:
     *   通知时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund_notify.notify_time
     *
     * @mbg.generated
     */
    private Date notifyTime;

    /**
     * Database Column Remarks:
     *   下次通知时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund_notify.next_notify_time
     *
     * @mbg.generated
     */
    private Date nextNotifyTime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund_notify.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   通知参数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund_notify.notify_arguments
     *
     * @mbg.generated
     */
    private String notifyArguments;

    /**
     * Database Column Remarks:
     *   通知返回结果
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_refund_notify.notify_result
     *
     * @mbg.generated
     */
    private String notifyResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund_notify.id
     *
     * @return the value of t_mmall_order_refund_notify.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund_notify.id
     *
     * @param id the value for t_mmall_order_refund_notify.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund_notify.user_id
     *
     * @return the value of t_mmall_order_refund_notify.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund_notify.user_id
     *
     * @param userId the value for t_mmall_order_refund_notify.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund_notify.order_no
     *
     * @return the value of t_mmall_order_refund_notify.order_no
     *
     * @mbg.generated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund_notify.order_no
     *
     * @param orderNo the value for t_mmall_order_refund_notify.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund_notify.vendor_id
     *
     * @return the value of t_mmall_order_refund_notify.vendor_id
     *
     * @mbg.generated
     */
    public Long getVendorId() {
        return vendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund_notify.vendor_id
     *
     * @param vendorId the value for t_mmall_order_refund_notify.vendor_id
     *
     * @mbg.generated
     */
    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund_notify.bind_id
     *
     * @return the value of t_mmall_order_refund_notify.bind_id
     *
     * @mbg.generated
     */
    public String getBindId() {
        return bindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund_notify.bind_id
     *
     * @param bindId the value for t_mmall_order_refund_notify.bind_id
     *
     * @mbg.generated
     */
    public void setBindId(String bindId) {
        this.bindId = bindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund_notify.notify_status
     *
     * @return the value of t_mmall_order_refund_notify.notify_status
     *
     * @mbg.generated
     */
    public Byte getNotifyStatus() {
        return notifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund_notify.notify_status
     *
     * @param notifyStatus the value for t_mmall_order_refund_notify.notify_status
     *
     * @mbg.generated
     */
    public void setNotifyStatus(Byte notifyStatus) {
        this.notifyStatus = notifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund_notify.notify_cnt
     *
     * @return the value of t_mmall_order_refund_notify.notify_cnt
     *
     * @mbg.generated
     */
    public Integer getNotifyCnt() {
        return notifyCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund_notify.notify_cnt
     *
     * @param notifyCnt the value for t_mmall_order_refund_notify.notify_cnt
     *
     * @mbg.generated
     */
    public void setNotifyCnt(Integer notifyCnt) {
        this.notifyCnt = notifyCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund_notify.notify_time
     *
     * @return the value of t_mmall_order_refund_notify.notify_time
     *
     * @mbg.generated
     */
    public Date getNotifyTime() {
        return notifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund_notify.notify_time
     *
     * @param notifyTime the value for t_mmall_order_refund_notify.notify_time
     *
     * @mbg.generated
     */
    public void setNotifyTime(Date notifyTime) {
        this.notifyTime = notifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund_notify.next_notify_time
     *
     * @return the value of t_mmall_order_refund_notify.next_notify_time
     *
     * @mbg.generated
     */
    public Date getNextNotifyTime() {
        return nextNotifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund_notify.next_notify_time
     *
     * @param nextNotifyTime the value for t_mmall_order_refund_notify.next_notify_time
     *
     * @mbg.generated
     */
    public void setNextNotifyTime(Date nextNotifyTime) {
        this.nextNotifyTime = nextNotifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund_notify.create_time
     *
     * @return the value of t_mmall_order_refund_notify.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund_notify.create_time
     *
     * @param createTime the value for t_mmall_order_refund_notify.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund_notify.notify_arguments
     *
     * @return the value of t_mmall_order_refund_notify.notify_arguments
     *
     * @mbg.generated
     */
    public String getNotifyArguments() {
        return notifyArguments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund_notify.notify_arguments
     *
     * @param notifyArguments the value for t_mmall_order_refund_notify.notify_arguments
     *
     * @mbg.generated
     */
    public void setNotifyArguments(String notifyArguments) {
        this.notifyArguments = notifyArguments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_refund_notify.notify_result
     *
     * @return the value of t_mmall_order_refund_notify.notify_result
     *
     * @mbg.generated
     */
    public String getNotifyResult() {
        return notifyResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_refund_notify.notify_result
     *
     * @param notifyResult the value for t_mmall_order_refund_notify.notify_result
     *
     * @mbg.generated
     */
    public void setNotifyResult(String notifyResult) {
        this.notifyResult = notifyResult;
    }
}