package com.mjj.orm.mybatis.demo.dto;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_mmall_order_trace
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TMmallOrderTrace extends BaseEntity {
    /**
     * Database Column Remarks:
     *   跟踪表主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_trace.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   节点修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_trace.node_modify_time
     *
     * @mbg.generated
     */
    private Date nodeModifyTime;

    /**
     * Database Column Remarks:
     *   节点状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_trace.node_status
     *
     * @mbg.generated
     */
    private Boolean nodeStatus;

    /**
     * Database Column Remarks:
     *   trace id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_trace.trace_id
     *
     * @mbg.generated
     */
    private String traceId;

    /**
     * Database Column Remarks:
     *   父节点标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_trace.parent_id
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     * Database Column Remarks:
     *   自身节点标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_trace.self_id
     *
     * @mbg.generated
     */
    private String selfId;

    /**
     * Database Column Remarks:
     *   节点创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_trace.node_create_time
     *
     * @mbg.generated
     */
    private Date nodeCreateTime;

    /**
     * Database Column Remarks:
     *   节点名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_trace.node_name
     *
     * @mbg.generated
     */
    private String nodeName;

    /**
     * Database Column Remarks:
     *   节点信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_trace.msg
     *
     * @mbg.generated
     */
    private String msg;

    /**
     * Database Column Remarks:
     *   节点处理url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_trace.notify_url
     *
     * @mbg.generated
     */
    private String notifyUrl;

    /**
     * Database Column Remarks:
     *   节点扩展信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_order_trace.ext
     *
     * @mbg.generated
     */
    private String ext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_trace.id
     *
     * @return the value of t_mmall_order_trace.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_trace.id
     *
     * @param id the value for t_mmall_order_trace.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_trace.node_modify_time
     *
     * @return the value of t_mmall_order_trace.node_modify_time
     *
     * @mbg.generated
     */
    public Date getNodeModifyTime() {
        return nodeModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_trace.node_modify_time
     *
     * @param nodeModifyTime the value for t_mmall_order_trace.node_modify_time
     *
     * @mbg.generated
     */
    public void setNodeModifyTime(Date nodeModifyTime) {
        this.nodeModifyTime = nodeModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_trace.node_status
     *
     * @return the value of t_mmall_order_trace.node_status
     *
     * @mbg.generated
     */
    public Boolean getNodeStatus() {
        return nodeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_trace.node_status
     *
     * @param nodeStatus the value for t_mmall_order_trace.node_status
     *
     * @mbg.generated
     */
    public void setNodeStatus(Boolean nodeStatus) {
        this.nodeStatus = nodeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_trace.trace_id
     *
     * @return the value of t_mmall_order_trace.trace_id
     *
     * @mbg.generated
     */
    public String getTraceId() {
        return traceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_trace.trace_id
     *
     * @param traceId the value for t_mmall_order_trace.trace_id
     *
     * @mbg.generated
     */
    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_trace.parent_id
     *
     * @return the value of t_mmall_order_trace.parent_id
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_trace.parent_id
     *
     * @param parentId the value for t_mmall_order_trace.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_trace.self_id
     *
     * @return the value of t_mmall_order_trace.self_id
     *
     * @mbg.generated
     */
    public String getSelfId() {
        return selfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_trace.self_id
     *
     * @param selfId the value for t_mmall_order_trace.self_id
     *
     * @mbg.generated
     */
    public void setSelfId(String selfId) {
        this.selfId = selfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_trace.node_create_time
     *
     * @return the value of t_mmall_order_trace.node_create_time
     *
     * @mbg.generated
     */
    public Date getNodeCreateTime() {
        return nodeCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_trace.node_create_time
     *
     * @param nodeCreateTime the value for t_mmall_order_trace.node_create_time
     *
     * @mbg.generated
     */
    public void setNodeCreateTime(Date nodeCreateTime) {
        this.nodeCreateTime = nodeCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_trace.node_name
     *
     * @return the value of t_mmall_order_trace.node_name
     *
     * @mbg.generated
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_trace.node_name
     *
     * @param nodeName the value for t_mmall_order_trace.node_name
     *
     * @mbg.generated
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_trace.msg
     *
     * @return the value of t_mmall_order_trace.msg
     *
     * @mbg.generated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_trace.msg
     *
     * @param msg the value for t_mmall_order_trace.msg
     *
     * @mbg.generated
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_trace.notify_url
     *
     * @return the value of t_mmall_order_trace.notify_url
     *
     * @mbg.generated
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_trace.notify_url
     *
     * @param notifyUrl the value for t_mmall_order_trace.notify_url
     *
     * @mbg.generated
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_order_trace.ext
     *
     * @return the value of t_mmall_order_trace.ext
     *
     * @mbg.generated
     */
    public String getExt() {
        return ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_order_trace.ext
     *
     * @param ext the value for t_mmall_order_trace.ext
     *
     * @mbg.generated
     */
    public void setExt(String ext) {
        this.ext = ext;
    }
}