package com.mjj.orm.mybatis.demo.dto;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_mmall_cps_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TMmallCpsInfo extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_cps_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   app包名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_cps_info.package_name
     *
     * @mbg.generated
     */
    private String packageName;

    /**
     * Database Column Remarks:
     *   app包名中文
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_cps_info.package_name_zh
     *
     * @mbg.generated
     */
    private String packageNameZh;

    /**
     * Database Column Remarks:
     *   cps_id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_cps_info.cps_id
     *
     * @mbg.generated
     */
    private String cpsId;

    /**
     * Database Column Remarks:
     *   cps名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_cps_info.cps_name
     *
     * @mbg.generated
     */
    private String cpsName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_cps_info.id
     *
     * @return the value of t_mmall_cps_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_cps_info.id
     *
     * @param id the value for t_mmall_cps_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_cps_info.package_name
     *
     * @return the value of t_mmall_cps_info.package_name
     *
     * @mbg.generated
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_cps_info.package_name
     *
     * @param packageName the value for t_mmall_cps_info.package_name
     *
     * @mbg.generated
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_cps_info.package_name_zh
     *
     * @return the value of t_mmall_cps_info.package_name_zh
     *
     * @mbg.generated
     */
    public String getPackageNameZh() {
        return packageNameZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_cps_info.package_name_zh
     *
     * @param packageNameZh the value for t_mmall_cps_info.package_name_zh
     *
     * @mbg.generated
     */
    public void setPackageNameZh(String packageNameZh) {
        this.packageNameZh = packageNameZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_cps_info.cps_id
     *
     * @return the value of t_mmall_cps_info.cps_id
     *
     * @mbg.generated
     */
    public String getCpsId() {
        return cpsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_cps_info.cps_id
     *
     * @param cpsId the value for t_mmall_cps_info.cps_id
     *
     * @mbg.generated
     */
    public void setCpsId(String cpsId) {
        this.cpsId = cpsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_cps_info.cps_name
     *
     * @return the value of t_mmall_cps_info.cps_name
     *
     * @mbg.generated
     */
    public String getCpsName() {
        return cpsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_cps_info.cps_name
     *
     * @param cpsName the value for t_mmall_cps_info.cps_name
     *
     * @mbg.generated
     */
    public void setCpsName(String cpsName) {
        this.cpsName = cpsName;
    }
}