package com.mjj.orm.mybatis.demo.dto;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_mmall_tencent_order
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TMmallTencentOrder extends BaseEntity {
    /**
     * Database Column Remarks:
     *   自增ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_tencent_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   乐购订单，多合一必传，单买和漫游时可不传
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_tencent_order.le_order_no
     *
     * @mbg.generated
     */
    private String leOrderNo;

    /**
     * Database Column Remarks:
     *   腾讯订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_tencent_order.tencent_order_no
     *
     * @mbg.generated
     */
    private String tencentOrderNo;

    /**
     * Database Column Remarks:
     *   乐视用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_tencent_order.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   腾讯虚拟用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_tencent_order.vuid
     *
     * @mbg.generated
     */
    private Long vuid;

    /**
     * Database Column Remarks:
     *   腾讯用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_tencent_order.tencent_uid
     *
     * @mbg.generated
     */
    private String tencentUid;

    /**
     * Database Column Remarks:
     *   订单价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_tencent_order.order_price
     *
     * @mbg.generated
     */
    private BigDecimal orderPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_tencent_order.tencent_price
     *
     * @mbg.generated
     */
    private BigDecimal tencentPrice;

    /**
     * Database Column Remarks:
     *   订单产品类型(100:会员,101:视频,102:专辑)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_tencent_order.product_type
     *
     * @mbg.generated
     */
    private Integer productType;

    /**
     * Database Column Remarks:
     *   订单类型(1:多合一,2:单买会员,3:漫游,4:单片购买)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_tencent_order.order_type
     *
     * @mbg.generated
     */
    private Integer orderType;

    /**
     * Database Column Remarks:
     *   订单产品名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_tencent_order.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     * Database Column Remarks:
     *   会员动作(0:无,1:开通会员,2:关闭会员)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_tencent_order.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_tencent_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_tencent_order.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_tencent_order.tencent_uid_type
     *
     * @mbg.generated
     */
    private String tencentUidType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mmall_tencent_order.ext
     *
     * @mbg.generated
     */
    private String ext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_tencent_order.id
     *
     * @return the value of t_mmall_tencent_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_tencent_order.id
     *
     * @param id the value for t_mmall_tencent_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_tencent_order.le_order_no
     *
     * @return the value of t_mmall_tencent_order.le_order_no
     *
     * @mbg.generated
     */
    public String getLeOrderNo() {
        return leOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_tencent_order.le_order_no
     *
     * @param leOrderNo the value for t_mmall_tencent_order.le_order_no
     *
     * @mbg.generated
     */
    public void setLeOrderNo(String leOrderNo) {
        this.leOrderNo = leOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_tencent_order.tencent_order_no
     *
     * @return the value of t_mmall_tencent_order.tencent_order_no
     *
     * @mbg.generated
     */
    public String getTencentOrderNo() {
        return tencentOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_tencent_order.tencent_order_no
     *
     * @param tencentOrderNo the value for t_mmall_tencent_order.tencent_order_no
     *
     * @mbg.generated
     */
    public void setTencentOrderNo(String tencentOrderNo) {
        this.tencentOrderNo = tencentOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_tencent_order.user_id
     *
     * @return the value of t_mmall_tencent_order.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_tencent_order.user_id
     *
     * @param userId the value for t_mmall_tencent_order.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_tencent_order.vuid
     *
     * @return the value of t_mmall_tencent_order.vuid
     *
     * @mbg.generated
     */
    public Long getVuid() {
        return vuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_tencent_order.vuid
     *
     * @param vuid the value for t_mmall_tencent_order.vuid
     *
     * @mbg.generated
     */
    public void setVuid(Long vuid) {
        this.vuid = vuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_tencent_order.tencent_uid
     *
     * @return the value of t_mmall_tencent_order.tencent_uid
     *
     * @mbg.generated
     */
    public String getTencentUid() {
        return tencentUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_tencent_order.tencent_uid
     *
     * @param tencentUid the value for t_mmall_tencent_order.tencent_uid
     *
     * @mbg.generated
     */
    public void setTencentUid(String tencentUid) {
        this.tencentUid = tencentUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_tencent_order.order_price
     *
     * @return the value of t_mmall_tencent_order.order_price
     *
     * @mbg.generated
     */
    public BigDecimal getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_tencent_order.order_price
     *
     * @param orderPrice the value for t_mmall_tencent_order.order_price
     *
     * @mbg.generated
     */
    public void setOrderPrice(BigDecimal orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_tencent_order.tencent_price
     *
     * @return the value of t_mmall_tencent_order.tencent_price
     *
     * @mbg.generated
     */
    public BigDecimal getTencentPrice() {
        return tencentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_tencent_order.tencent_price
     *
     * @param tencentPrice the value for t_mmall_tencent_order.tencent_price
     *
     * @mbg.generated
     */
    public void setTencentPrice(BigDecimal tencentPrice) {
        this.tencentPrice = tencentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_tencent_order.product_type
     *
     * @return the value of t_mmall_tencent_order.product_type
     *
     * @mbg.generated
     */
    public Integer getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_tencent_order.product_type
     *
     * @param productType the value for t_mmall_tencent_order.product_type
     *
     * @mbg.generated
     */
    public void setProductType(Integer productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_tencent_order.order_type
     *
     * @return the value of t_mmall_tencent_order.order_type
     *
     * @mbg.generated
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_tencent_order.order_type
     *
     * @param orderType the value for t_mmall_tencent_order.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_tencent_order.product_name
     *
     * @return the value of t_mmall_tencent_order.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_tencent_order.product_name
     *
     * @param productName the value for t_mmall_tencent_order.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_tencent_order.type
     *
     * @return the value of t_mmall_tencent_order.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_tencent_order.type
     *
     * @param type the value for t_mmall_tencent_order.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_tencent_order.create_time
     *
     * @return the value of t_mmall_tencent_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_tencent_order.create_time
     *
     * @param createTime the value for t_mmall_tencent_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_tencent_order.modify_time
     *
     * @return the value of t_mmall_tencent_order.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_tencent_order.modify_time
     *
     * @param modifyTime the value for t_mmall_tencent_order.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_tencent_order.tencent_uid_type
     *
     * @return the value of t_mmall_tencent_order.tencent_uid_type
     *
     * @mbg.generated
     */
    public String getTencentUidType() {
        return tencentUidType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_tencent_order.tencent_uid_type
     *
     * @param tencentUidType the value for t_mmall_tencent_order.tencent_uid_type
     *
     * @mbg.generated
     */
    public void setTencentUidType(String tencentUidType) {
        this.tencentUidType = tencentUidType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mmall_tencent_order.ext
     *
     * @return the value of t_mmall_tencent_order.ext
     *
     * @mbg.generated
     */
    public String getExt() {
        return ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mmall_tencent_order.ext
     *
     * @param ext the value for t_mmall_tencent_order.ext
     *
     * @mbg.generated
     */
    public void setExt(String ext) {
        this.ext = ext;
    }
}