package com.mjj.orm.mybatis.demo.dto;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_operation_gift_order
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TOperationGiftOrder extends BaseEntity {
    /**
     * Database Column Remarks:
     *   自增主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_gift_order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   联运赠送订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_gift_order.orderNo
     *
     * @mbg.generated
     */
    private String orderno;

    /**
     * Database Column Remarks:
     *   赠送币种类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_gift_order.giftType
     *
     * @mbg.generated
     */
    private Byte gifttype;

    /**
     * Database Column Remarks:
     *   赠送价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_gift_order.giftPrice
     *
     * @mbg.generated
     */
    private BigDecimal giftprice;

    /**
     * Database Column Remarks:
     *   订单状态：0-初始 1-已支付 2-已退款 3-支付失败 4-退款中
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_gift_order.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   来源方订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_gift_order.sourceOrderId
     *
     * @mbg.generated
     */
    private String sourceorderid;

    /**
     * Database Column Remarks:
     *   来源方产品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_gift_order.sourceRequirementId
     *
     * @mbg.generated
     */
    private String sourcerequirementid;

    /**
     * Database Column Remarks:
     *   来源方产品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_gift_order.sourceRequirementName
     *
     * @mbg.generated
     */
    private String sourcerequirementname;

    /**
     * Database Column Remarks:
     *   来源方系统Id 1 乐购
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_gift_order.sourceSystemId
     *
     * @mbg.generated
     */
    private Byte sourcesystemid;

    /**
     * Database Column Remarks:
     *   来源方系统名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_gift_order.sourceSystem
     *
     * @mbg.generated
     */
    private String sourcesystem;

    /**
     * Database Column Remarks:
     *   用户名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_gift_order.userName
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_gift_order.userId
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     * Database Column Remarks:
     *   订单创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_gift_order.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * Database Column Remarks:
     *   订单支付时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_gift_order.payTime
     *
     * @mbg.generated
     */
    private Date paytime;

    /**
     * Database Column Remarks:
     *   金钻平台订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_gift_order.virtualOrderId
     *
     * @mbg.generated
     */
    private String virtualorderid;

    /**
     * Database Column Remarks:
     *   来源方系统的业务id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_gift_order.sourceSystemSecondId
     *
     * @mbg.generated
     */
    private String sourcesystemsecondid;

    /**
     * Database Column Remarks:
     *   来源方系统的业务名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_gift_order.sourceSystemSecondName
     *
     * @mbg.generated
     */
    private String sourcesystemsecondname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_gift_order.id
     *
     * @return the value of t_operation_gift_order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_gift_order.id
     *
     * @param id the value for t_operation_gift_order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_gift_order.orderNo
     *
     * @return the value of t_operation_gift_order.orderNo
     *
     * @mbg.generated
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_gift_order.orderNo
     *
     * @param orderno the value for t_operation_gift_order.orderNo
     *
     * @mbg.generated
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_gift_order.giftType
     *
     * @return the value of t_operation_gift_order.giftType
     *
     * @mbg.generated
     */
    public Byte getGifttype() {
        return gifttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_gift_order.giftType
     *
     * @param gifttype the value for t_operation_gift_order.giftType
     *
     * @mbg.generated
     */
    public void setGifttype(Byte gifttype) {
        this.gifttype = gifttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_gift_order.giftPrice
     *
     * @return the value of t_operation_gift_order.giftPrice
     *
     * @mbg.generated
     */
    public BigDecimal getGiftprice() {
        return giftprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_gift_order.giftPrice
     *
     * @param giftprice the value for t_operation_gift_order.giftPrice
     *
     * @mbg.generated
     */
    public void setGiftprice(BigDecimal giftprice) {
        this.giftprice = giftprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_gift_order.status
     *
     * @return the value of t_operation_gift_order.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_gift_order.status
     *
     * @param status the value for t_operation_gift_order.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_gift_order.sourceOrderId
     *
     * @return the value of t_operation_gift_order.sourceOrderId
     *
     * @mbg.generated
     */
    public String getSourceorderid() {
        return sourceorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_gift_order.sourceOrderId
     *
     * @param sourceorderid the value for t_operation_gift_order.sourceOrderId
     *
     * @mbg.generated
     */
    public void setSourceorderid(String sourceorderid) {
        this.sourceorderid = sourceorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_gift_order.sourceRequirementId
     *
     * @return the value of t_operation_gift_order.sourceRequirementId
     *
     * @mbg.generated
     */
    public String getSourcerequirementid() {
        return sourcerequirementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_gift_order.sourceRequirementId
     *
     * @param sourcerequirementid the value for t_operation_gift_order.sourceRequirementId
     *
     * @mbg.generated
     */
    public void setSourcerequirementid(String sourcerequirementid) {
        this.sourcerequirementid = sourcerequirementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_gift_order.sourceRequirementName
     *
     * @return the value of t_operation_gift_order.sourceRequirementName
     *
     * @mbg.generated
     */
    public String getSourcerequirementname() {
        return sourcerequirementname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_gift_order.sourceRequirementName
     *
     * @param sourcerequirementname the value for t_operation_gift_order.sourceRequirementName
     *
     * @mbg.generated
     */
    public void setSourcerequirementname(String sourcerequirementname) {
        this.sourcerequirementname = sourcerequirementname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_gift_order.sourceSystemId
     *
     * @return the value of t_operation_gift_order.sourceSystemId
     *
     * @mbg.generated
     */
    public Byte getSourcesystemid() {
        return sourcesystemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_gift_order.sourceSystemId
     *
     * @param sourcesystemid the value for t_operation_gift_order.sourceSystemId
     *
     * @mbg.generated
     */
    public void setSourcesystemid(Byte sourcesystemid) {
        this.sourcesystemid = sourcesystemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_gift_order.sourceSystem
     *
     * @return the value of t_operation_gift_order.sourceSystem
     *
     * @mbg.generated
     */
    public String getSourcesystem() {
        return sourcesystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_gift_order.sourceSystem
     *
     * @param sourcesystem the value for t_operation_gift_order.sourceSystem
     *
     * @mbg.generated
     */
    public void setSourcesystem(String sourcesystem) {
        this.sourcesystem = sourcesystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_gift_order.userName
     *
     * @return the value of t_operation_gift_order.userName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_gift_order.userName
     *
     * @param username the value for t_operation_gift_order.userName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_gift_order.userId
     *
     * @return the value of t_operation_gift_order.userId
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_gift_order.userId
     *
     * @param userid the value for t_operation_gift_order.userId
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_gift_order.createTime
     *
     * @return the value of t_operation_gift_order.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_gift_order.createTime
     *
     * @param createtime the value for t_operation_gift_order.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_gift_order.payTime
     *
     * @return the value of t_operation_gift_order.payTime
     *
     * @mbg.generated
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_gift_order.payTime
     *
     * @param paytime the value for t_operation_gift_order.payTime
     *
     * @mbg.generated
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_gift_order.virtualOrderId
     *
     * @return the value of t_operation_gift_order.virtualOrderId
     *
     * @mbg.generated
     */
    public String getVirtualorderid() {
        return virtualorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_gift_order.virtualOrderId
     *
     * @param virtualorderid the value for t_operation_gift_order.virtualOrderId
     *
     * @mbg.generated
     */
    public void setVirtualorderid(String virtualorderid) {
        this.virtualorderid = virtualorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_gift_order.sourceSystemSecondId
     *
     * @return the value of t_operation_gift_order.sourceSystemSecondId
     *
     * @mbg.generated
     */
    public String getSourcesystemsecondid() {
        return sourcesystemsecondid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_gift_order.sourceSystemSecondId
     *
     * @param sourcesystemsecondid the value for t_operation_gift_order.sourceSystemSecondId
     *
     * @mbg.generated
     */
    public void setSourcesystemsecondid(String sourcesystemsecondid) {
        this.sourcesystemsecondid = sourcesystemsecondid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_gift_order.sourceSystemSecondName
     *
     * @return the value of t_operation_gift_order.sourceSystemSecondName
     *
     * @mbg.generated
     */
    public String getSourcesystemsecondname() {
        return sourcesystemsecondname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_gift_order.sourceSystemSecondName
     *
     * @param sourcesystemsecondname the value for t_operation_gift_order.sourceSystemSecondName
     *
     * @mbg.generated
     */
    public void setSourcesystemsecondname(String sourcesystemsecondname) {
        this.sourcesystemsecondname = sourcesystemsecondname;
    }
}