package com.mjj.orm.mybatis.demo.dto;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_operation_merchant
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TOperationMerchant extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_merchant.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   商户号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_merchant.merchantNo
     *
     * @mbg.generated
     */
    private String merchantno;

    /**
     * Database Column Remarks:
     *   商户密钥
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_merchant.secretKey
     *
     * @mbg.generated
     */
    private String secretkey;

    /**
     * Database Column Remarks:
     *   应用Key
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_merchant.appKey
     *
     * @mbg.generated
     */
    private String appkey;

    /**
     * Database Column Remarks:
     *   应用ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_merchant.appId
     *
     * @mbg.generated
     */
    private String appid;

    /**
     * Database Column Remarks:
     *   应用名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_merchant.appName
     *
     * @mbg.generated
     */
    private String appname;

    /**
     * Database Column Remarks:
     *   包名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_merchant.packageName
     *
     * @mbg.generated
     */
    private String packagename;

    /**
     * Database Column Remarks:
     *   支付回调地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_merchant.payCallbackUrl
     *
     * @mbg.generated
     */
    private String paycallbackurl;

    /**
     * Database Column Remarks:
     *   退款回调地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_merchant.refundCallbackUrl
     *
     * @mbg.generated
     */
    private String refundcallbackurl;

    /**
     * Database Column Remarks:
     *   分成比例
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_merchant.rate
     *
     * @mbg.generated
     */
    private BigDecimal rate;

    /**
     * Database Column Remarks:
     *   供应商编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_merchant.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   开发者用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_merchant.userCenterId
     *
     * @mbg.generated
     */
    private String usercenterid;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_merchant.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_merchant.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * Database Column Remarks:
     *   虚拟币分成比例
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_merchant.goldRate
     *
     * @mbg.generated
     */
    private BigDecimal goldrate;

    /**
     * Database Column Remarks:
     *   开发者用户名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_merchant.userCenterName
     *
     * @mbg.generated
     */
    private String usercentername;

    /**
     * Database Column Remarks:
     *   付费应用下载分成比例
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_merchant.payDownloadRate
     *
     * @mbg.generated
     */
    private BigDecimal paydownloadrate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_merchant.id
     *
     * @return the value of t_operation_merchant.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_merchant.id
     *
     * @param id the value for t_operation_merchant.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_merchant.merchantNo
     *
     * @return the value of t_operation_merchant.merchantNo
     *
     * @mbg.generated
     */
    public String getMerchantno() {
        return merchantno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_merchant.merchantNo
     *
     * @param merchantno the value for t_operation_merchant.merchantNo
     *
     * @mbg.generated
     */
    public void setMerchantno(String merchantno) {
        this.merchantno = merchantno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_merchant.secretKey
     *
     * @return the value of t_operation_merchant.secretKey
     *
     * @mbg.generated
     */
    public String getSecretkey() {
        return secretkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_merchant.secretKey
     *
     * @param secretkey the value for t_operation_merchant.secretKey
     *
     * @mbg.generated
     */
    public void setSecretkey(String secretkey) {
        this.secretkey = secretkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_merchant.appKey
     *
     * @return the value of t_operation_merchant.appKey
     *
     * @mbg.generated
     */
    public String getAppkey() {
        return appkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_merchant.appKey
     *
     * @param appkey the value for t_operation_merchant.appKey
     *
     * @mbg.generated
     */
    public void setAppkey(String appkey) {
        this.appkey = appkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_merchant.appId
     *
     * @return the value of t_operation_merchant.appId
     *
     * @mbg.generated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_merchant.appId
     *
     * @param appid the value for t_operation_merchant.appId
     *
     * @mbg.generated
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_merchant.appName
     *
     * @return the value of t_operation_merchant.appName
     *
     * @mbg.generated
     */
    public String getAppname() {
        return appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_merchant.appName
     *
     * @param appname the value for t_operation_merchant.appName
     *
     * @mbg.generated
     */
    public void setAppname(String appname) {
        this.appname = appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_merchant.packageName
     *
     * @return the value of t_operation_merchant.packageName
     *
     * @mbg.generated
     */
    public String getPackagename() {
        return packagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_merchant.packageName
     *
     * @param packagename the value for t_operation_merchant.packageName
     *
     * @mbg.generated
     */
    public void setPackagename(String packagename) {
        this.packagename = packagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_merchant.payCallbackUrl
     *
     * @return the value of t_operation_merchant.payCallbackUrl
     *
     * @mbg.generated
     */
    public String getPaycallbackurl() {
        return paycallbackurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_merchant.payCallbackUrl
     *
     * @param paycallbackurl the value for t_operation_merchant.payCallbackUrl
     *
     * @mbg.generated
     */
    public void setPaycallbackurl(String paycallbackurl) {
        this.paycallbackurl = paycallbackurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_merchant.refundCallbackUrl
     *
     * @return the value of t_operation_merchant.refundCallbackUrl
     *
     * @mbg.generated
     */
    public String getRefundcallbackurl() {
        return refundcallbackurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_merchant.refundCallbackUrl
     *
     * @param refundcallbackurl the value for t_operation_merchant.refundCallbackUrl
     *
     * @mbg.generated
     */
    public void setRefundcallbackurl(String refundcallbackurl) {
        this.refundcallbackurl = refundcallbackurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_merchant.rate
     *
     * @return the value of t_operation_merchant.rate
     *
     * @mbg.generated
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_merchant.rate
     *
     * @param rate the value for t_operation_merchant.rate
     *
     * @mbg.generated
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_merchant.code
     *
     * @return the value of t_operation_merchant.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_merchant.code
     *
     * @param code the value for t_operation_merchant.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_merchant.userCenterId
     *
     * @return the value of t_operation_merchant.userCenterId
     *
     * @mbg.generated
     */
    public String getUsercenterid() {
        return usercenterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_merchant.userCenterId
     *
     * @param usercenterid the value for t_operation_merchant.userCenterId
     *
     * @mbg.generated
     */
    public void setUsercenterid(String usercenterid) {
        this.usercenterid = usercenterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_merchant.updateTime
     *
     * @return the value of t_operation_merchant.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_merchant.updateTime
     *
     * @param updatetime the value for t_operation_merchant.updateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_merchant.createTime
     *
     * @return the value of t_operation_merchant.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_merchant.createTime
     *
     * @param createtime the value for t_operation_merchant.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_merchant.goldRate
     *
     * @return the value of t_operation_merchant.goldRate
     *
     * @mbg.generated
     */
    public BigDecimal getGoldrate() {
        return goldrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_merchant.goldRate
     *
     * @param goldrate the value for t_operation_merchant.goldRate
     *
     * @mbg.generated
     */
    public void setGoldrate(BigDecimal goldrate) {
        this.goldrate = goldrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_merchant.userCenterName
     *
     * @return the value of t_operation_merchant.userCenterName
     *
     * @mbg.generated
     */
    public String getUsercentername() {
        return usercentername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_merchant.userCenterName
     *
     * @param usercentername the value for t_operation_merchant.userCenterName
     *
     * @mbg.generated
     */
    public void setUsercentername(String usercentername) {
        this.usercentername = usercentername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_merchant.payDownloadRate
     *
     * @return the value of t_operation_merchant.payDownloadRate
     *
     * @mbg.generated
     */
    public BigDecimal getPaydownloadrate() {
        return paydownloadrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_merchant.payDownloadRate
     *
     * @param paydownloadrate the value for t_operation_merchant.payDownloadRate
     *
     * @mbg.generated
     */
    public void setPaydownloadrate(BigDecimal paydownloadrate) {
        this.paydownloadrate = paydownloadrate;
    }
}