package com.mjj.orm.mybatis.demo.dto;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_operation_product
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TOperationProduct extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   第三方业务产品ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.externalProductId
     *
     * @mbg.generated
     */
    private String externalproductid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.sku
     *
     * @mbg.generated
     */
    private String sku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.appKey
     *
     * @mbg.generated
     */
    private String appkey;

    /**
     * Database Column Remarks:
     *   产品描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   产品价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.displayPrice
     *
     * @mbg.generated
     */
    private BigDecimal displayprice;

    /**
     * Database Column Remarks:
     *   最大数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.maxQuantity
     *
     * @mbg.generated
     */
    private Integer maxquantity;

    /**
     * Database Column Remarks:
     *   产品分类  10:专辑 11:视频 12:打包套餐
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.productCategory
     *
     * @mbg.generated
     */
    private String productcategory;

    /**
     * Database Column Remarks:
     *   产品类型(0:普通SKU,1:家庭会员SKU)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.productType
     *
     * @mbg.generated
     */
    private String producttype;

    /**
     * Database Column Remarks:
     *   产品状态：0-上架  1-下架
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.fulfillmentType
     *
     * @mbg.generated
     */
    private Integer fulfillmenttype;

    /**
     * Database Column Remarks:
     *   产品图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.prdImg
     *
     * @mbg.generated
     */
    private String prdimg;

    /**
     * Database Column Remarks:
     *   下载地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.downloadUrl
     *
     * @mbg.generated
     */
    private String downloadurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.appId
     *
     * @mbg.generated
     */
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.accType
     *
     * @mbg.generated
     */
    private String acctype;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.createdBy
     *
     * @mbg.generated
     */
    private String createdby;

    /**
     * Database Column Remarks:
     *   修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.updatedBy
     *
     * @mbg.generated
     */
    private String updatedby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.startActiveTime
     *
     * @mbg.generated
     */
    private Date startactivetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.endActiveTime
     *
     * @mbg.generated
     */
    private Date endactivetime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * Database Column Remarks:
     *   分成金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_product.benefitPrice
     *
     * @mbg.generated
     */
    private BigDecimal benefitprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.id
     *
     * @return the value of t_operation_product.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.id
     *
     * @param id the value for t_operation_product.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.externalProductId
     *
     * @return the value of t_operation_product.externalProductId
     *
     * @mbg.generated
     */
    public String getExternalproductid() {
        return externalproductid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.externalProductId
     *
     * @param externalproductid the value for t_operation_product.externalProductId
     *
     * @mbg.generated
     */
    public void setExternalproductid(String externalproductid) {
        this.externalproductid = externalproductid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.sku
     *
     * @return the value of t_operation_product.sku
     *
     * @mbg.generated
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.sku
     *
     * @param sku the value for t_operation_product.sku
     *
     * @mbg.generated
     */
    public void setSku(String sku) {
        this.sku = sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.appKey
     *
     * @return the value of t_operation_product.appKey
     *
     * @mbg.generated
     */
    public String getAppkey() {
        return appkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.appKey
     *
     * @param appkey the value for t_operation_product.appKey
     *
     * @mbg.generated
     */
    public void setAppkey(String appkey) {
        this.appkey = appkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.description
     *
     * @return the value of t_operation_product.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.description
     *
     * @param description the value for t_operation_product.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.displayPrice
     *
     * @return the value of t_operation_product.displayPrice
     *
     * @mbg.generated
     */
    public BigDecimal getDisplayprice() {
        return displayprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.displayPrice
     *
     * @param displayprice the value for t_operation_product.displayPrice
     *
     * @mbg.generated
     */
    public void setDisplayprice(BigDecimal displayprice) {
        this.displayprice = displayprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.maxQuantity
     *
     * @return the value of t_operation_product.maxQuantity
     *
     * @mbg.generated
     */
    public Integer getMaxquantity() {
        return maxquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.maxQuantity
     *
     * @param maxquantity the value for t_operation_product.maxQuantity
     *
     * @mbg.generated
     */
    public void setMaxquantity(Integer maxquantity) {
        this.maxquantity = maxquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.productCategory
     *
     * @return the value of t_operation_product.productCategory
     *
     * @mbg.generated
     */
    public String getProductcategory() {
        return productcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.productCategory
     *
     * @param productcategory the value for t_operation_product.productCategory
     *
     * @mbg.generated
     */
    public void setProductcategory(String productcategory) {
        this.productcategory = productcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.productType
     *
     * @return the value of t_operation_product.productType
     *
     * @mbg.generated
     */
    public String getProducttype() {
        return producttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.productType
     *
     * @param producttype the value for t_operation_product.productType
     *
     * @mbg.generated
     */
    public void setProducttype(String producttype) {
        this.producttype = producttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.status
     *
     * @return the value of t_operation_product.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.status
     *
     * @param status the value for t_operation_product.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.fulfillmentType
     *
     * @return the value of t_operation_product.fulfillmentType
     *
     * @mbg.generated
     */
    public Integer getFulfillmenttype() {
        return fulfillmenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.fulfillmentType
     *
     * @param fulfillmenttype the value for t_operation_product.fulfillmentType
     *
     * @mbg.generated
     */
    public void setFulfillmenttype(Integer fulfillmenttype) {
        this.fulfillmenttype = fulfillmenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.prdImg
     *
     * @return the value of t_operation_product.prdImg
     *
     * @mbg.generated
     */
    public String getPrdimg() {
        return prdimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.prdImg
     *
     * @param prdimg the value for t_operation_product.prdImg
     *
     * @mbg.generated
     */
    public void setPrdimg(String prdimg) {
        this.prdimg = prdimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.downloadUrl
     *
     * @return the value of t_operation_product.downloadUrl
     *
     * @mbg.generated
     */
    public String getDownloadurl() {
        return downloadurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.downloadUrl
     *
     * @param downloadurl the value for t_operation_product.downloadUrl
     *
     * @mbg.generated
     */
    public void setDownloadurl(String downloadurl) {
        this.downloadurl = downloadurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.appId
     *
     * @return the value of t_operation_product.appId
     *
     * @mbg.generated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.appId
     *
     * @param appid the value for t_operation_product.appId
     *
     * @mbg.generated
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.accType
     *
     * @return the value of t_operation_product.accType
     *
     * @mbg.generated
     */
    public String getAcctype() {
        return acctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.accType
     *
     * @param acctype the value for t_operation_product.accType
     *
     * @mbg.generated
     */
    public void setAcctype(String acctype) {
        this.acctype = acctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.createdBy
     *
     * @return the value of t_operation_product.createdBy
     *
     * @mbg.generated
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.createdBy
     *
     * @param createdby the value for t_operation_product.createdBy
     *
     * @mbg.generated
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.updatedBy
     *
     * @return the value of t_operation_product.updatedBy
     *
     * @mbg.generated
     */
    public String getUpdatedby() {
        return updatedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.updatedBy
     *
     * @param updatedby the value for t_operation_product.updatedBy
     *
     * @mbg.generated
     */
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.startActiveTime
     *
     * @return the value of t_operation_product.startActiveTime
     *
     * @mbg.generated
     */
    public Date getStartactivetime() {
        return startactivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.startActiveTime
     *
     * @param startactivetime the value for t_operation_product.startActiveTime
     *
     * @mbg.generated
     */
    public void setStartactivetime(Date startactivetime) {
        this.startactivetime = startactivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.endActiveTime
     *
     * @return the value of t_operation_product.endActiveTime
     *
     * @mbg.generated
     */
    public Date getEndactivetime() {
        return endactivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.endActiveTime
     *
     * @param endactivetime the value for t_operation_product.endActiveTime
     *
     * @mbg.generated
     */
    public void setEndactivetime(Date endactivetime) {
        this.endactivetime = endactivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.createTime
     *
     * @return the value of t_operation_product.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.createTime
     *
     * @param createtime the value for t_operation_product.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.updateTime
     *
     * @return the value of t_operation_product.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.updateTime
     *
     * @param updatetime the value for t_operation_product.updateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_product.benefitPrice
     *
     * @return the value of t_operation_product.benefitPrice
     *
     * @mbg.generated
     */
    public BigDecimal getBenefitprice() {
        return benefitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_product.benefitPrice
     *
     * @param benefitprice the value for t_operation_product.benefitPrice
     *
     * @mbg.generated
     */
    public void setBenefitprice(BigDecimal benefitprice) {
        this.benefitprice = benefitprice;
    }
}