package com.mjj.orm.mybatis.demo.dto;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_operation_refund
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TOperationRefund extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_refund.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   退款订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_refund.refundNo
     *
     * @mbg.generated
     */
    private String refundno;

    /**
     * Database Column Remarks:
     *   业务订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_refund.orderNo
     *
     * @mbg.generated
     */
    private String orderno;

    /**
     * Database Column Remarks:
     *   第三方业务订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_refund.externalRefundNo
     *
     * @mbg.generated
     */
    private String externalrefundno;

    /**
     * Database Column Remarks:
     *   退款状态：0-初始 1-已退款
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_refund.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_refund.userId
     *
     * @mbg.generated
     */
    private String userid;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_refund.userName
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   退款金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_refund.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   支付订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_refund.lepayRefundNo
     *
     * @mbg.generated
     */
    private String lepayrefundno;

    /**
     * Database Column Remarks:
     *   应用key
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_refund.appKey
     *
     * @mbg.generated
     */
    private String appkey;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_refund.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation_refund.refundTime
     *
     * @mbg.generated
     */
    private Date refundtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_refund.id
     *
     * @return the value of t_operation_refund.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_refund.id
     *
     * @param id the value for t_operation_refund.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_refund.refundNo
     *
     * @return the value of t_operation_refund.refundNo
     *
     * @mbg.generated
     */
    public String getRefundno() {
        return refundno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_refund.refundNo
     *
     * @param refundno the value for t_operation_refund.refundNo
     *
     * @mbg.generated
     */
    public void setRefundno(String refundno) {
        this.refundno = refundno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_refund.orderNo
     *
     * @return the value of t_operation_refund.orderNo
     *
     * @mbg.generated
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_refund.orderNo
     *
     * @param orderno the value for t_operation_refund.orderNo
     *
     * @mbg.generated
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_refund.externalRefundNo
     *
     * @return the value of t_operation_refund.externalRefundNo
     *
     * @mbg.generated
     */
    public String getExternalrefundno() {
        return externalrefundno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_refund.externalRefundNo
     *
     * @param externalrefundno the value for t_operation_refund.externalRefundNo
     *
     * @mbg.generated
     */
    public void setExternalrefundno(String externalrefundno) {
        this.externalrefundno = externalrefundno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_refund.status
     *
     * @return the value of t_operation_refund.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_refund.status
     *
     * @param status the value for t_operation_refund.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_refund.userId
     *
     * @return the value of t_operation_refund.userId
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_refund.userId
     *
     * @param userid the value for t_operation_refund.userId
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_refund.userName
     *
     * @return the value of t_operation_refund.userName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_refund.userName
     *
     * @param username the value for t_operation_refund.userName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_refund.price
     *
     * @return the value of t_operation_refund.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_refund.price
     *
     * @param price the value for t_operation_refund.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_refund.lepayRefundNo
     *
     * @return the value of t_operation_refund.lepayRefundNo
     *
     * @mbg.generated
     */
    public String getLepayrefundno() {
        return lepayrefundno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_refund.lepayRefundNo
     *
     * @param lepayrefundno the value for t_operation_refund.lepayRefundNo
     *
     * @mbg.generated
     */
    public void setLepayrefundno(String lepayrefundno) {
        this.lepayrefundno = lepayrefundno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_refund.appKey
     *
     * @return the value of t_operation_refund.appKey
     *
     * @mbg.generated
     */
    public String getAppkey() {
        return appkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_refund.appKey
     *
     * @param appkey the value for t_operation_refund.appKey
     *
     * @mbg.generated
     */
    public void setAppkey(String appkey) {
        this.appkey = appkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_refund.createTime
     *
     * @return the value of t_operation_refund.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_refund.createTime
     *
     * @param createtime the value for t_operation_refund.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation_refund.refundTime
     *
     * @return the value of t_operation_refund.refundTime
     *
     * @mbg.generated
     */
    public Date getRefundtime() {
        return refundtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation_refund.refundTime
     *
     * @param refundtime the value for t_operation_refund.refundTime
     *
     * @mbg.generated
     */
    public void setRefundtime(Date refundtime) {
        this.refundtime = refundtime;
    }
}