package com.mjj.orm.mybatis.demo.dto;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_real_time_tj
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TRealTimeTj extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_real_time_tj.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_real_time_tj.geo
     *
     * @mbg.generated
     */
    private String geo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_real_time_tj.geo_order_count
     *
     * @mbg.generated
     */
    private Integer geoOrderCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_real_time_tj.geo_order_income
     *
     * @mbg.generated
     */
    private BigDecimal geoOrderIncome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_real_time_tj.pay_business_no
     *
     * @mbg.generated
     */
    private Integer payBusinessNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_real_time_tj.pbn_order_count
     *
     * @mbg.generated
     */
    private Integer pbnOrderCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_real_time_tj.pbn_order_income
     *
     * @mbg.generated
     */
    private BigDecimal pbnOrderIncome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_real_time_tj.machine_type
     *
     * @mbg.generated
     */
    private String machineType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_real_time_tj.machine_order_count
     *
     * @mbg.generated
     */
    private Integer machineOrderCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_real_time_tj.machine_order_income
     *
     * @mbg.generated
     */
    private BigDecimal machineOrderIncome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_real_time_tj.package_name
     *
     * @mbg.generated
     */
    private String packageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_real_time_tj.package_name_order_count
     *
     * @mbg.generated
     */
    private Integer packageNameOrderCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_real_time_tj.package_name_order_income
     *
     * @mbg.generated
     */
    private BigDecimal packageNameOrderIncome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_real_time_tj.cps_id
     *
     * @mbg.generated
     */
    private String cpsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_real_time_tj.cps_id_order_count
     *
     * @mbg.generated
     */
    private Integer cpsIdOrderCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_real_time_tj.cps_id_order_income
     *
     * @mbg.generated
     */
    private BigDecimal cpsIdOrderIncome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_real_time_tj.date_type
     *
     * @mbg.generated
     */
    private Integer dateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_real_time_tj.business_type
     *
     * @mbg.generated
     */
    private Integer businessType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_real_time_tj.date
     *
     * @return the value of t_real_time_tj.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_real_time_tj.date
     *
     * @param date the value for t_real_time_tj.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_real_time_tj.geo
     *
     * @return the value of t_real_time_tj.geo
     *
     * @mbg.generated
     */
    public String getGeo() {
        return geo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_real_time_tj.geo
     *
     * @param geo the value for t_real_time_tj.geo
     *
     * @mbg.generated
     */
    public void setGeo(String geo) {
        this.geo = geo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_real_time_tj.geo_order_count
     *
     * @return the value of t_real_time_tj.geo_order_count
     *
     * @mbg.generated
     */
    public Integer getGeoOrderCount() {
        return geoOrderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_real_time_tj.geo_order_count
     *
     * @param geoOrderCount the value for t_real_time_tj.geo_order_count
     *
     * @mbg.generated
     */
    public void setGeoOrderCount(Integer geoOrderCount) {
        this.geoOrderCount = geoOrderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_real_time_tj.geo_order_income
     *
     * @return the value of t_real_time_tj.geo_order_income
     *
     * @mbg.generated
     */
    public BigDecimal getGeoOrderIncome() {
        return geoOrderIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_real_time_tj.geo_order_income
     *
     * @param geoOrderIncome the value for t_real_time_tj.geo_order_income
     *
     * @mbg.generated
     */
    public void setGeoOrderIncome(BigDecimal geoOrderIncome) {
        this.geoOrderIncome = geoOrderIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_real_time_tj.pay_business_no
     *
     * @return the value of t_real_time_tj.pay_business_no
     *
     * @mbg.generated
     */
    public Integer getPayBusinessNo() {
        return payBusinessNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_real_time_tj.pay_business_no
     *
     * @param payBusinessNo the value for t_real_time_tj.pay_business_no
     *
     * @mbg.generated
     */
    public void setPayBusinessNo(Integer payBusinessNo) {
        this.payBusinessNo = payBusinessNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_real_time_tj.pbn_order_count
     *
     * @return the value of t_real_time_tj.pbn_order_count
     *
     * @mbg.generated
     */
    public Integer getPbnOrderCount() {
        return pbnOrderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_real_time_tj.pbn_order_count
     *
     * @param pbnOrderCount the value for t_real_time_tj.pbn_order_count
     *
     * @mbg.generated
     */
    public void setPbnOrderCount(Integer pbnOrderCount) {
        this.pbnOrderCount = pbnOrderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_real_time_tj.pbn_order_income
     *
     * @return the value of t_real_time_tj.pbn_order_income
     *
     * @mbg.generated
     */
    public BigDecimal getPbnOrderIncome() {
        return pbnOrderIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_real_time_tj.pbn_order_income
     *
     * @param pbnOrderIncome the value for t_real_time_tj.pbn_order_income
     *
     * @mbg.generated
     */
    public void setPbnOrderIncome(BigDecimal pbnOrderIncome) {
        this.pbnOrderIncome = pbnOrderIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_real_time_tj.machine_type
     *
     * @return the value of t_real_time_tj.machine_type
     *
     * @mbg.generated
     */
    public String getMachineType() {
        return machineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_real_time_tj.machine_type
     *
     * @param machineType the value for t_real_time_tj.machine_type
     *
     * @mbg.generated
     */
    public void setMachineType(String machineType) {
        this.machineType = machineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_real_time_tj.machine_order_count
     *
     * @return the value of t_real_time_tj.machine_order_count
     *
     * @mbg.generated
     */
    public Integer getMachineOrderCount() {
        return machineOrderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_real_time_tj.machine_order_count
     *
     * @param machineOrderCount the value for t_real_time_tj.machine_order_count
     *
     * @mbg.generated
     */
    public void setMachineOrderCount(Integer machineOrderCount) {
        this.machineOrderCount = machineOrderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_real_time_tj.machine_order_income
     *
     * @return the value of t_real_time_tj.machine_order_income
     *
     * @mbg.generated
     */
    public BigDecimal getMachineOrderIncome() {
        return machineOrderIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_real_time_tj.machine_order_income
     *
     * @param machineOrderIncome the value for t_real_time_tj.machine_order_income
     *
     * @mbg.generated
     */
    public void setMachineOrderIncome(BigDecimal machineOrderIncome) {
        this.machineOrderIncome = machineOrderIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_real_time_tj.package_name
     *
     * @return the value of t_real_time_tj.package_name
     *
     * @mbg.generated
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_real_time_tj.package_name
     *
     * @param packageName the value for t_real_time_tj.package_name
     *
     * @mbg.generated
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_real_time_tj.package_name_order_count
     *
     * @return the value of t_real_time_tj.package_name_order_count
     *
     * @mbg.generated
     */
    public Integer getPackageNameOrderCount() {
        return packageNameOrderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_real_time_tj.package_name_order_count
     *
     * @param packageNameOrderCount the value for t_real_time_tj.package_name_order_count
     *
     * @mbg.generated
     */
    public void setPackageNameOrderCount(Integer packageNameOrderCount) {
        this.packageNameOrderCount = packageNameOrderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_real_time_tj.package_name_order_income
     *
     * @return the value of t_real_time_tj.package_name_order_income
     *
     * @mbg.generated
     */
    public BigDecimal getPackageNameOrderIncome() {
        return packageNameOrderIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_real_time_tj.package_name_order_income
     *
     * @param packageNameOrderIncome the value for t_real_time_tj.package_name_order_income
     *
     * @mbg.generated
     */
    public void setPackageNameOrderIncome(BigDecimal packageNameOrderIncome) {
        this.packageNameOrderIncome = packageNameOrderIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_real_time_tj.cps_id
     *
     * @return the value of t_real_time_tj.cps_id
     *
     * @mbg.generated
     */
    public String getCpsId() {
        return cpsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_real_time_tj.cps_id
     *
     * @param cpsId the value for t_real_time_tj.cps_id
     *
     * @mbg.generated
     */
    public void setCpsId(String cpsId) {
        this.cpsId = cpsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_real_time_tj.cps_id_order_count
     *
     * @return the value of t_real_time_tj.cps_id_order_count
     *
     * @mbg.generated
     */
    public Integer getCpsIdOrderCount() {
        return cpsIdOrderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_real_time_tj.cps_id_order_count
     *
     * @param cpsIdOrderCount the value for t_real_time_tj.cps_id_order_count
     *
     * @mbg.generated
     */
    public void setCpsIdOrderCount(Integer cpsIdOrderCount) {
        this.cpsIdOrderCount = cpsIdOrderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_real_time_tj.cps_id_order_income
     *
     * @return the value of t_real_time_tj.cps_id_order_income
     *
     * @mbg.generated
     */
    public BigDecimal getCpsIdOrderIncome() {
        return cpsIdOrderIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_real_time_tj.cps_id_order_income
     *
     * @param cpsIdOrderIncome the value for t_real_time_tj.cps_id_order_income
     *
     * @mbg.generated
     */
    public void setCpsIdOrderIncome(BigDecimal cpsIdOrderIncome) {
        this.cpsIdOrderIncome = cpsIdOrderIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_real_time_tj.date_type
     *
     * @return the value of t_real_time_tj.date_type
     *
     * @mbg.generated
     */
    public Integer getDateType() {
        return dateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_real_time_tj.date_type
     *
     * @param dateType the value for t_real_time_tj.date_type
     *
     * @mbg.generated
     */
    public void setDateType(Integer dateType) {
        this.dateType = dateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_real_time_tj.business_type
     *
     * @return the value of t_real_time_tj.business_type
     *
     * @mbg.generated
     */
    public Integer getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_real_time_tj.business_type
     *
     * @param businessType the value for t_real_time_tj.business_type
     *
     * @mbg.generated
     */
    public void setBusinessType(Integer businessType) {
        this.businessType = businessType;
    }
}