package com.mjj.orm.mybatis.demo.dto;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_sku
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TSku extends BaseEntity {
    /**
     * Database Column Remarks:
     *   自增ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   物料编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.product_item_code
     *
     * @mbg.generated
     */
    private String productItemCode;

    /**
     * Database Column Remarks:
     *   1 华视超影 2 超级家庭会员 3 单卖会员 4 亲子会员 5 付费轮播
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.sku_type
     *
     * @mbg.generated
     */
    private Integer skuType;

    /**
     * Database Column Remarks:
     *   spu下sku排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   SKU是否预售 0非预售 1预售
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.is_pre_sale
     *
     * @mbg.generated
     */
    private Boolean isPreSale;

    /**
     * Database Column Remarks:
     *   预售宣传图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.pre_sale_image
     *
     * @mbg.generated
     */
    private String preSaleImage;

    /**
     * Database Column Remarks:
     *   尾款金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.final_payment
     *
     * @mbg.generated
     */
    private BigDecimal finalPayment;

    /**
     * Database Column Remarks:
     *   预售定金结束时间，只有预售是不为空
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.down_payment_time
     *
     * @mbg.generated
     */
    private Date downPaymentTime;

    /**
     * Database Column Remarks:
     *   定金
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.down_payment
     *
     * @mbg.generated
     */
    private BigDecimal downPayment;

    /**
     * Database Column Remarks:
     *   SKU 编码(唯一)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.sku_no
     *
     * @mbg.generated
     */
    private String skuNo;

    /**
     * Database Column Remarks:
     *   1级品类ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.category_id_1
     *
     * @mbg.generated
     */
    private Long categoryId1;

    /**
     * Database Column Remarks:
     *   2级品类ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.category_id_2
     *
     * @mbg.generated
     */
    private Long categoryId2;

    /**
     * Database Column Remarks:
     *   3级品类ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.category_id_3
     *
     * @mbg.generated
     */
    private Long categoryId3;

    /**
     * Database Column Remarks:
     *   直接所属品类ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.category_id
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     * Database Column Remarks:
     *   SKU名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   SKU显示名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.show_name
     *
     * @mbg.generated
     */
    private String showName;

    /**
     * Database Column Remarks:
     *   sku售卖价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.price_info
     *
     * @mbg.generated
     */
    private String priceInfo;

    /**
     * Database Column Remarks:
     *   sku市场价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.market_price
     *
     * @mbg.generated
     */
    private BigDecimal marketPrice;

    /**
     * Database Column Remarks:
     *   69码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.code_69
     *
     * @mbg.generated
     */
    private String code69;

    /**
     * Database Column Remarks:
     *   发票型号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.receipt_model
     *
     * @mbg.generated
     */
    private String receiptModel;

    /**
     * Database Column Remarks:
     *   发票商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.receipt_name
     *
     * @mbg.generated
     */
    private String receiptName;

    /**
     * Database Column Remarks:
     *   SPU的ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.spu_id
     *
     * @mbg.generated
     */
    private Long spuId;

    /**
     * Database Column Remarks:
     *   SPU编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.spu_no
     *
     * @mbg.generated
     */
    private String spuNo;

    /**
     * Database Column Remarks:
     *   乐范成长值描述，不做数据运算
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.lefan_val
     *
     * @mbg.generated
     */
    private String lefanVal;

    /**
     * Database Column Remarks:
     *   使用规则
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.introduction
     *
     * @mbg.generated
     */
    private String introduction;

    /**
     * Database Column Remarks:
     *   商品描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   上架标识(1下架2上架)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.is_online
     *
     * @mbg.generated
     */
    private Byte isOnline;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     * Database Column Remarks:
     *   修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.modify_user
     *
     * @mbg.generated
     */
    private String modifyUser;

    /**
     * Database Column Remarks:
     *   商家收款号（支付系统分配）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.sku_pay_id
     *
     * @mbg.generated
     */
    private String skuPayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.img_urls
     *
     * @mbg.generated
     */
    private String imgUrls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.business_id
     *
     * @mbg.generated
     */
    private String businessId;

    /**
     * Database Column Remarks:
     *   审计人审计时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.review_time
     *
     * @mbg.generated
     */
    private Date reviewTime;

    /**
     * Database Column Remarks:
     *   sku商户信息审计人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.reviewer
     *
     * @mbg.generated
     */
    private String reviewer;

    /**
     * Database Column Remarks:
     *   是否为自动续费，0否，1是，默认是否
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.is_auto_renewal
     *
     * @mbg.generated
     */
    private Byte isAutoRenewal;

    /**
     * Database Column Remarks:
     *   预售尾款结束时间，预售时不为空
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.final_payment_time
     *
     * @mbg.generated
     */
    private Date finalPaymentTime;

    /**
     * Database Column Remarks:
     *   推广类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.promotion_type
     *
     * @mbg.generated
     */
    private Integer promotionType;

    /**
     * Database Column Remarks:
     *   子skuno 仅在自动续费时需要
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.sub_sku_no
     *
     * @mbg.generated
     */
    private String subSkuNo;

    /**
     * Database Column Remarks:
     *   是否包含首月促销，0不包含，1包含
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.is_contains_promotion
     *
     * @mbg.generated
     */
    private Byte isContainsPromotion;

    /**
     * Database Column Remarks:
     *   父sku 仅在自动续费时需要
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.super_sku_no
     *
     * @mbg.generated
     */
    private String superSkuNo;

    /**
     * Database Column Remarks:
     *   sku活动时间描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.activity_time_description
     *
     * @mbg.generated
     */
    private String activityTimeDescription;

    /**
     * Database Column Remarks:
     *   组合频道描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.group_channels_description
     *
     * @mbg.generated
     */
    private String groupChannelsDescription;

    /**
     * Database Column Remarks:
     *   自动续费提示文案
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.renewal_reminder_time
     *
     * @mbg.generated
     */
    private Integer renewalReminderTime;

    /**
     * Database Column Remarks:
     *   自动续费描述文案
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.renewal_description
     *
     * @mbg.generated
     */
    private String renewalDescription;

    /**
     * Database Column Remarks:
     *   试看文案
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.pre_see_description
     *
     * @mbg.generated
     */
    private String preSeeDescription;

    /**
     * Database Column Remarks:
     *   是否使用权益会员价格 默认0 不使用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.is_use_le_plus_price
     *
     * @mbg.generated
     */
    private Integer isUseLePlusPrice;

    /**
     * Database Column Remarks:
     *   权益会员价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.le_plus_price
     *
     * @mbg.generated
     */
    private BigDecimal lePlusPrice;

    /**
     * Database Column Remarks:
     *   权益会员成功页
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.le_plus_images
     *
     * @mbg.generated
     */
    private String lePlusImages;

    /**
     * Database Column Remarks:
     *   角标图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.corner_mark_images
     *
     * @mbg.generated
     */
    private String cornerMarkImages;

    /**
     * Database Column Remarks:
     *   会员类型
     *   1 华影时光
     *   2 超级家庭会员
     *   3 付费轮播会员
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.vip_type
     *
     * @mbg.generated
     */
    private Integer vipType;

    /**
     * Database Column Remarks:
     *   会员名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.vip_name
     *
     * @mbg.generated
     */
    private String vipName;

    /**
     * Database Column Remarks:
     *   是否出现在首屏
     *   0 默认不出现
     *   1 出现在首屏
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.is_show_first_screen
     *
     * @mbg.generated
     */
    private Integer isShowFirstScreen;

    /**
     * Database Column Remarks:
     *   收银台3特殊的展示名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.show_name_cashier
     *
     * @mbg.generated
     */
    private String showNameCashier;

    /**
     * Database Column Remarks:
     *   收银台3兼容模板图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.img_urls_cashier
     *
     * @mbg.generated
     */
    private String imgUrlsCashier;

    /**
     * Database Column Remarks:
     *   支付渠道
     *   1微信
     *   2支付宝
     *   1,2 微信/支付宝都支持
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.pay_channel
     *
     * @mbg.generated
     */
    private String payChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku.sku_attribute
     *
     * @mbg.generated
     */
    private String skuAttribute;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.id
     *
     * @return the value of t_sku.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.id
     *
     * @param id the value for t_sku.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.product_item_code
     *
     * @return the value of t_sku.product_item_code
     *
     * @mbg.generated
     */
    public String getProductItemCode() {
        return productItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.product_item_code
     *
     * @param productItemCode the value for t_sku.product_item_code
     *
     * @mbg.generated
     */
    public void setProductItemCode(String productItemCode) {
        this.productItemCode = productItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.sku_type
     *
     * @return the value of t_sku.sku_type
     *
     * @mbg.generated
     */
    public Integer getSkuType() {
        return skuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.sku_type
     *
     * @param skuType the value for t_sku.sku_type
     *
     * @mbg.generated
     */
    public void setSkuType(Integer skuType) {
        this.skuType = skuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.sort
     *
     * @return the value of t_sku.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.sort
     *
     * @param sort the value for t_sku.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.is_pre_sale
     *
     * @return the value of t_sku.is_pre_sale
     *
     * @mbg.generated
     */
    public Boolean getIsPreSale() {
        return isPreSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.is_pre_sale
     *
     * @param isPreSale the value for t_sku.is_pre_sale
     *
     * @mbg.generated
     */
    public void setIsPreSale(Boolean isPreSale) {
        this.isPreSale = isPreSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.pre_sale_image
     *
     * @return the value of t_sku.pre_sale_image
     *
     * @mbg.generated
     */
    public String getPreSaleImage() {
        return preSaleImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.pre_sale_image
     *
     * @param preSaleImage the value for t_sku.pre_sale_image
     *
     * @mbg.generated
     */
    public void setPreSaleImage(String preSaleImage) {
        this.preSaleImage = preSaleImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.final_payment
     *
     * @return the value of t_sku.final_payment
     *
     * @mbg.generated
     */
    public BigDecimal getFinalPayment() {
        return finalPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.final_payment
     *
     * @param finalPayment the value for t_sku.final_payment
     *
     * @mbg.generated
     */
    public void setFinalPayment(BigDecimal finalPayment) {
        this.finalPayment = finalPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.down_payment_time
     *
     * @return the value of t_sku.down_payment_time
     *
     * @mbg.generated
     */
    public Date getDownPaymentTime() {
        return downPaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.down_payment_time
     *
     * @param downPaymentTime the value for t_sku.down_payment_time
     *
     * @mbg.generated
     */
    public void setDownPaymentTime(Date downPaymentTime) {
        this.downPaymentTime = downPaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.down_payment
     *
     * @return the value of t_sku.down_payment
     *
     * @mbg.generated
     */
    public BigDecimal getDownPayment() {
        return downPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.down_payment
     *
     * @param downPayment the value for t_sku.down_payment
     *
     * @mbg.generated
     */
    public void setDownPayment(BigDecimal downPayment) {
        this.downPayment = downPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.sku_no
     *
     * @return the value of t_sku.sku_no
     *
     * @mbg.generated
     */
    public String getSkuNo() {
        return skuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.sku_no
     *
     * @param skuNo the value for t_sku.sku_no
     *
     * @mbg.generated
     */
    public void setSkuNo(String skuNo) {
        this.skuNo = skuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.category_id_1
     *
     * @return the value of t_sku.category_id_1
     *
     * @mbg.generated
     */
    public Long getCategoryId1() {
        return categoryId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.category_id_1
     *
     * @param categoryId1 the value for t_sku.category_id_1
     *
     * @mbg.generated
     */
    public void setCategoryId1(Long categoryId1) {
        this.categoryId1 = categoryId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.category_id_2
     *
     * @return the value of t_sku.category_id_2
     *
     * @mbg.generated
     */
    public Long getCategoryId2() {
        return categoryId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.category_id_2
     *
     * @param categoryId2 the value for t_sku.category_id_2
     *
     * @mbg.generated
     */
    public void setCategoryId2(Long categoryId2) {
        this.categoryId2 = categoryId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.category_id_3
     *
     * @return the value of t_sku.category_id_3
     *
     * @mbg.generated
     */
    public Long getCategoryId3() {
        return categoryId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.category_id_3
     *
     * @param categoryId3 the value for t_sku.category_id_3
     *
     * @mbg.generated
     */
    public void setCategoryId3(Long categoryId3) {
        this.categoryId3 = categoryId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.category_id
     *
     * @return the value of t_sku.category_id
     *
     * @mbg.generated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.category_id
     *
     * @param categoryId the value for t_sku.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.name
     *
     * @return the value of t_sku.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.name
     *
     * @param name the value for t_sku.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.show_name
     *
     * @return the value of t_sku.show_name
     *
     * @mbg.generated
     */
    public String getShowName() {
        return showName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.show_name
     *
     * @param showName the value for t_sku.show_name
     *
     * @mbg.generated
     */
    public void setShowName(String showName) {
        this.showName = showName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.price
     *
     * @return the value of t_sku.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.price
     *
     * @param price the value for t_sku.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.price_info
     *
     * @return the value of t_sku.price_info
     *
     * @mbg.generated
     */
    public String getPriceInfo() {
        return priceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.price_info
     *
     * @param priceInfo the value for t_sku.price_info
     *
     * @mbg.generated
     */
    public void setPriceInfo(String priceInfo) {
        this.priceInfo = priceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.market_price
     *
     * @return the value of t_sku.market_price
     *
     * @mbg.generated
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.market_price
     *
     * @param marketPrice the value for t_sku.market_price
     *
     * @mbg.generated
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.code_69
     *
     * @return the value of t_sku.code_69
     *
     * @mbg.generated
     */
    public String getCode69() {
        return code69;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.code_69
     *
     * @param code69 the value for t_sku.code_69
     *
     * @mbg.generated
     */
    public void setCode69(String code69) {
        this.code69 = code69;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.receipt_model
     *
     * @return the value of t_sku.receipt_model
     *
     * @mbg.generated
     */
    public String getReceiptModel() {
        return receiptModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.receipt_model
     *
     * @param receiptModel the value for t_sku.receipt_model
     *
     * @mbg.generated
     */
    public void setReceiptModel(String receiptModel) {
        this.receiptModel = receiptModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.receipt_name
     *
     * @return the value of t_sku.receipt_name
     *
     * @mbg.generated
     */
    public String getReceiptName() {
        return receiptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.receipt_name
     *
     * @param receiptName the value for t_sku.receipt_name
     *
     * @mbg.generated
     */
    public void setReceiptName(String receiptName) {
        this.receiptName = receiptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.spu_id
     *
     * @return the value of t_sku.spu_id
     *
     * @mbg.generated
     */
    public Long getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.spu_id
     *
     * @param spuId the value for t_sku.spu_id
     *
     * @mbg.generated
     */
    public void setSpuId(Long spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.spu_no
     *
     * @return the value of t_sku.spu_no
     *
     * @mbg.generated
     */
    public String getSpuNo() {
        return spuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.spu_no
     *
     * @param spuNo the value for t_sku.spu_no
     *
     * @mbg.generated
     */
    public void setSpuNo(String spuNo) {
        this.spuNo = spuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.lefan_val
     *
     * @return the value of t_sku.lefan_val
     *
     * @mbg.generated
     */
    public String getLefanVal() {
        return lefanVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.lefan_val
     *
     * @param lefanVal the value for t_sku.lefan_val
     *
     * @mbg.generated
     */
    public void setLefanVal(String lefanVal) {
        this.lefanVal = lefanVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.introduction
     *
     * @return the value of t_sku.introduction
     *
     * @mbg.generated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.introduction
     *
     * @param introduction the value for t_sku.introduction
     *
     * @mbg.generated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.description
     *
     * @return the value of t_sku.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.description
     *
     * @param description the value for t_sku.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.is_online
     *
     * @return the value of t_sku.is_online
     *
     * @mbg.generated
     */
    public Byte getIsOnline() {
        return isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.is_online
     *
     * @param isOnline the value for t_sku.is_online
     *
     * @mbg.generated
     */
    public void setIsOnline(Byte isOnline) {
        this.isOnline = isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.create_time
     *
     * @return the value of t_sku.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.create_time
     *
     * @param createTime the value for t_sku.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.modify_time
     *
     * @return the value of t_sku.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.modify_time
     *
     * @param modifyTime the value for t_sku.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.create_user
     *
     * @return the value of t_sku.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.create_user
     *
     * @param createUser the value for t_sku.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.modify_user
     *
     * @return the value of t_sku.modify_user
     *
     * @mbg.generated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.modify_user
     *
     * @param modifyUser the value for t_sku.modify_user
     *
     * @mbg.generated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.sku_pay_id
     *
     * @return the value of t_sku.sku_pay_id
     *
     * @mbg.generated
     */
    public String getSkuPayId() {
        return skuPayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.sku_pay_id
     *
     * @param skuPayId the value for t_sku.sku_pay_id
     *
     * @mbg.generated
     */
    public void setSkuPayId(String skuPayId) {
        this.skuPayId = skuPayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.img_urls
     *
     * @return the value of t_sku.img_urls
     *
     * @mbg.generated
     */
    public String getImgUrls() {
        return imgUrls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.img_urls
     *
     * @param imgUrls the value for t_sku.img_urls
     *
     * @mbg.generated
     */
    public void setImgUrls(String imgUrls) {
        this.imgUrls = imgUrls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.business_id
     *
     * @return the value of t_sku.business_id
     *
     * @mbg.generated
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.business_id
     *
     * @param businessId the value for t_sku.business_id
     *
     * @mbg.generated
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.review_time
     *
     * @return the value of t_sku.review_time
     *
     * @mbg.generated
     */
    public Date getReviewTime() {
        return reviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.review_time
     *
     * @param reviewTime the value for t_sku.review_time
     *
     * @mbg.generated
     */
    public void setReviewTime(Date reviewTime) {
        this.reviewTime = reviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.reviewer
     *
     * @return the value of t_sku.reviewer
     *
     * @mbg.generated
     */
    public String getReviewer() {
        return reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.reviewer
     *
     * @param reviewer the value for t_sku.reviewer
     *
     * @mbg.generated
     */
    public void setReviewer(String reviewer) {
        this.reviewer = reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.is_auto_renewal
     *
     * @return the value of t_sku.is_auto_renewal
     *
     * @mbg.generated
     */
    public Byte getIsAutoRenewal() {
        return isAutoRenewal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.is_auto_renewal
     *
     * @param isAutoRenewal the value for t_sku.is_auto_renewal
     *
     * @mbg.generated
     */
    public void setIsAutoRenewal(Byte isAutoRenewal) {
        this.isAutoRenewal = isAutoRenewal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.final_payment_time
     *
     * @return the value of t_sku.final_payment_time
     *
     * @mbg.generated
     */
    public Date getFinalPaymentTime() {
        return finalPaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.final_payment_time
     *
     * @param finalPaymentTime the value for t_sku.final_payment_time
     *
     * @mbg.generated
     */
    public void setFinalPaymentTime(Date finalPaymentTime) {
        this.finalPaymentTime = finalPaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.promotion_type
     *
     * @return the value of t_sku.promotion_type
     *
     * @mbg.generated
     */
    public Integer getPromotionType() {
        return promotionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.promotion_type
     *
     * @param promotionType the value for t_sku.promotion_type
     *
     * @mbg.generated
     */
    public void setPromotionType(Integer promotionType) {
        this.promotionType = promotionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.sub_sku_no
     *
     * @return the value of t_sku.sub_sku_no
     *
     * @mbg.generated
     */
    public String getSubSkuNo() {
        return subSkuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.sub_sku_no
     *
     * @param subSkuNo the value for t_sku.sub_sku_no
     *
     * @mbg.generated
     */
    public void setSubSkuNo(String subSkuNo) {
        this.subSkuNo = subSkuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.is_contains_promotion
     *
     * @return the value of t_sku.is_contains_promotion
     *
     * @mbg.generated
     */
    public Byte getIsContainsPromotion() {
        return isContainsPromotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.is_contains_promotion
     *
     * @param isContainsPromotion the value for t_sku.is_contains_promotion
     *
     * @mbg.generated
     */
    public void setIsContainsPromotion(Byte isContainsPromotion) {
        this.isContainsPromotion = isContainsPromotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.super_sku_no
     *
     * @return the value of t_sku.super_sku_no
     *
     * @mbg.generated
     */
    public String getSuperSkuNo() {
        return superSkuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.super_sku_no
     *
     * @param superSkuNo the value for t_sku.super_sku_no
     *
     * @mbg.generated
     */
    public void setSuperSkuNo(String superSkuNo) {
        this.superSkuNo = superSkuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.activity_time_description
     *
     * @return the value of t_sku.activity_time_description
     *
     * @mbg.generated
     */
    public String getActivityTimeDescription() {
        return activityTimeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.activity_time_description
     *
     * @param activityTimeDescription the value for t_sku.activity_time_description
     *
     * @mbg.generated
     */
    public void setActivityTimeDescription(String activityTimeDescription) {
        this.activityTimeDescription = activityTimeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.group_channels_description
     *
     * @return the value of t_sku.group_channels_description
     *
     * @mbg.generated
     */
    public String getGroupChannelsDescription() {
        return groupChannelsDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.group_channels_description
     *
     * @param groupChannelsDescription the value for t_sku.group_channels_description
     *
     * @mbg.generated
     */
    public void setGroupChannelsDescription(String groupChannelsDescription) {
        this.groupChannelsDescription = groupChannelsDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.renewal_reminder_time
     *
     * @return the value of t_sku.renewal_reminder_time
     *
     * @mbg.generated
     */
    public Integer getRenewalReminderTime() {
        return renewalReminderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.renewal_reminder_time
     *
     * @param renewalReminderTime the value for t_sku.renewal_reminder_time
     *
     * @mbg.generated
     */
    public void setRenewalReminderTime(Integer renewalReminderTime) {
        this.renewalReminderTime = renewalReminderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.renewal_description
     *
     * @return the value of t_sku.renewal_description
     *
     * @mbg.generated
     */
    public String getRenewalDescription() {
        return renewalDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.renewal_description
     *
     * @param renewalDescription the value for t_sku.renewal_description
     *
     * @mbg.generated
     */
    public void setRenewalDescription(String renewalDescription) {
        this.renewalDescription = renewalDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.pre_see_description
     *
     * @return the value of t_sku.pre_see_description
     *
     * @mbg.generated
     */
    public String getPreSeeDescription() {
        return preSeeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.pre_see_description
     *
     * @param preSeeDescription the value for t_sku.pre_see_description
     *
     * @mbg.generated
     */
    public void setPreSeeDescription(String preSeeDescription) {
        this.preSeeDescription = preSeeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.is_use_le_plus_price
     *
     * @return the value of t_sku.is_use_le_plus_price
     *
     * @mbg.generated
     */
    public Integer getIsUseLePlusPrice() {
        return isUseLePlusPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.is_use_le_plus_price
     *
     * @param isUseLePlusPrice the value for t_sku.is_use_le_plus_price
     *
     * @mbg.generated
     */
    public void setIsUseLePlusPrice(Integer isUseLePlusPrice) {
        this.isUseLePlusPrice = isUseLePlusPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.le_plus_price
     *
     * @return the value of t_sku.le_plus_price
     *
     * @mbg.generated
     */
    public BigDecimal getLePlusPrice() {
        return lePlusPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.le_plus_price
     *
     * @param lePlusPrice the value for t_sku.le_plus_price
     *
     * @mbg.generated
     */
    public void setLePlusPrice(BigDecimal lePlusPrice) {
        this.lePlusPrice = lePlusPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.le_plus_images
     *
     * @return the value of t_sku.le_plus_images
     *
     * @mbg.generated
     */
    public String getLePlusImages() {
        return lePlusImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.le_plus_images
     *
     * @param lePlusImages the value for t_sku.le_plus_images
     *
     * @mbg.generated
     */
    public void setLePlusImages(String lePlusImages) {
        this.lePlusImages = lePlusImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.corner_mark_images
     *
     * @return the value of t_sku.corner_mark_images
     *
     * @mbg.generated
     */
    public String getCornerMarkImages() {
        return cornerMarkImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.corner_mark_images
     *
     * @param cornerMarkImages the value for t_sku.corner_mark_images
     *
     * @mbg.generated
     */
    public void setCornerMarkImages(String cornerMarkImages) {
        this.cornerMarkImages = cornerMarkImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.vip_type
     *
     * @return the value of t_sku.vip_type
     *
     * @mbg.generated
     */
    public Integer getVipType() {
        return vipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.vip_type
     *
     * @param vipType the value for t_sku.vip_type
     *
     * @mbg.generated
     */
    public void setVipType(Integer vipType) {
        this.vipType = vipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.vip_name
     *
     * @return the value of t_sku.vip_name
     *
     * @mbg.generated
     */
    public String getVipName() {
        return vipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.vip_name
     *
     * @param vipName the value for t_sku.vip_name
     *
     * @mbg.generated
     */
    public void setVipName(String vipName) {
        this.vipName = vipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.is_show_first_screen
     *
     * @return the value of t_sku.is_show_first_screen
     *
     * @mbg.generated
     */
    public Integer getIsShowFirstScreen() {
        return isShowFirstScreen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.is_show_first_screen
     *
     * @param isShowFirstScreen the value for t_sku.is_show_first_screen
     *
     * @mbg.generated
     */
    public void setIsShowFirstScreen(Integer isShowFirstScreen) {
        this.isShowFirstScreen = isShowFirstScreen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.show_name_cashier
     *
     * @return the value of t_sku.show_name_cashier
     *
     * @mbg.generated
     */
    public String getShowNameCashier() {
        return showNameCashier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.show_name_cashier
     *
     * @param showNameCashier the value for t_sku.show_name_cashier
     *
     * @mbg.generated
     */
    public void setShowNameCashier(String showNameCashier) {
        this.showNameCashier = showNameCashier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.img_urls_cashier
     *
     * @return the value of t_sku.img_urls_cashier
     *
     * @mbg.generated
     */
    public String getImgUrlsCashier() {
        return imgUrlsCashier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.img_urls_cashier
     *
     * @param imgUrlsCashier the value for t_sku.img_urls_cashier
     *
     * @mbg.generated
     */
    public void setImgUrlsCashier(String imgUrlsCashier) {
        this.imgUrlsCashier = imgUrlsCashier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.pay_channel
     *
     * @return the value of t_sku.pay_channel
     *
     * @mbg.generated
     */
    public String getPayChannel() {
        return payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.pay_channel
     *
     * @param payChannel the value for t_sku.pay_channel
     *
     * @mbg.generated
     */
    public void setPayChannel(String payChannel) {
        this.payChannel = payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku.sku_attribute
     *
     * @return the value of t_sku.sku_attribute
     *
     * @mbg.generated
     */
    public String getSkuAttribute() {
        return skuAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku.sku_attribute
     *
     * @param skuAttribute the value for t_sku.sku_attribute
     *
     * @mbg.generated
     */
    public void setSkuAttribute(String skuAttribute) {
        this.skuAttribute = skuAttribute;
    }
}