package com.mjj.orm.mybatis.demo.dto;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_sync_erp
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TSyncErp extends BaseEntity {
    /**
     * Database Column Remarks:
     *   自增ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   业务线
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.pay_business_no
     *
     * @mbg.generated
     */
    private String payBusinessNo;

    /**
     * Database Column Remarks:
     *   售卖价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   非会员分成金额，非会员总额乘以分成比例
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.non_member_benefit_price
     *
     * @mbg.generated
     */
    private BigDecimal nonMemberBenefitPrice;

    /**
     * Database Column Remarks:
     *   审计价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.audit_price
     *
     * @mbg.generated
     */
    private BigDecimal auditPrice;

    /**
     * Database Column Remarks:
     *   应用名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.app_name
     *
     * @mbg.generated
     */
    private String appName;

    /**
     * Database Column Remarks:
     *   供应商编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.vendor_code
     *
     * @mbg.generated
     */
    private String vendorCode;

    /**
     * Database Column Remarks:
     *   分成比例
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.vendor_rate
     *
     * @mbg.generated
     */
    private BigDecimal vendorRate;

    /**
     * Database Column Remarks:
     *   商户号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.merchant_no
     *
     * @mbg.generated
     */
    private String merchantNo;

    /**
     * Database Column Remarks:
     *   推送月份
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.push_month
     *
     * @mbg.generated
     */
    private String pushMonth;

    /**
     * Database Column Remarks:
     *   审计状态(0：未审计，1：审计中，2：审计完成，3：审计失败)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.audit_status
     *
     * @mbg.generated
     */
    private Byte auditStatus;

    /**
     * Database Column Remarks:
     *   导入erp状态(0：未导入，1：导入中，2：导入完成，3：导入失败，4：待重新导入)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.erp_status
     *
     * @mbg.generated
     */
    private Byte erpStatus;

    /**
     * Database Column Remarks:
     *   erp错误消息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.erp_error_message
     *
     * @mbg.generated
     */
    private String erpErrorMessage;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   父支付渠道
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.pay_parent_channel
     *
     * @mbg.generated
     */
    private Byte payParentChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.erp_group_id
     *
     * @mbg.generated
     */
    private String erpGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.journal_key
     *
     * @mbg.generated
     */
    private String journalKey;

    /**
     * Database Column Remarks:
     *   家庭会员分成金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.member_benefit_price
     *
     * @mbg.generated
     */
    private BigDecimal memberBenefitPrice;

    /**
     * Database Column Remarks:
     *   总的分成价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.total_benefit_price
     *
     * @mbg.generated
     */
    private BigDecimal totalBenefitPrice;

    /**
     * Database Column Remarks:
     *   0-app内付费购买内容,1-下载app类付费,2-金钻
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.push_erp_type
     *
     * @mbg.generated
     */
    private Byte pushErpType;

    /**
     * Database Column Remarks:
     *   0:应用类 1:游戏类 2:乐钻 10:大屏专辑 11:大屏视频 12:大屏打包套餐
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_erp.businessId
     *
     * @mbg.generated
     */
    private Byte businessid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.id
     *
     * @return the value of t_sync_erp.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.id
     *
     * @param id the value for t_sync_erp.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.pay_business_no
     *
     * @return the value of t_sync_erp.pay_business_no
     *
     * @mbg.generated
     */
    public String getPayBusinessNo() {
        return payBusinessNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.pay_business_no
     *
     * @param payBusinessNo the value for t_sync_erp.pay_business_no
     *
     * @mbg.generated
     */
    public void setPayBusinessNo(String payBusinessNo) {
        this.payBusinessNo = payBusinessNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.price
     *
     * @return the value of t_sync_erp.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.price
     *
     * @param price the value for t_sync_erp.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.non_member_benefit_price
     *
     * @return the value of t_sync_erp.non_member_benefit_price
     *
     * @mbg.generated
     */
    public BigDecimal getNonMemberBenefitPrice() {
        return nonMemberBenefitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.non_member_benefit_price
     *
     * @param nonMemberBenefitPrice the value for t_sync_erp.non_member_benefit_price
     *
     * @mbg.generated
     */
    public void setNonMemberBenefitPrice(BigDecimal nonMemberBenefitPrice) {
        this.nonMemberBenefitPrice = nonMemberBenefitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.audit_price
     *
     * @return the value of t_sync_erp.audit_price
     *
     * @mbg.generated
     */
    public BigDecimal getAuditPrice() {
        return auditPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.audit_price
     *
     * @param auditPrice the value for t_sync_erp.audit_price
     *
     * @mbg.generated
     */
    public void setAuditPrice(BigDecimal auditPrice) {
        this.auditPrice = auditPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.app_name
     *
     * @return the value of t_sync_erp.app_name
     *
     * @mbg.generated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.app_name
     *
     * @param appName the value for t_sync_erp.app_name
     *
     * @mbg.generated
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.vendor_code
     *
     * @return the value of t_sync_erp.vendor_code
     *
     * @mbg.generated
     */
    public String getVendorCode() {
        return vendorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.vendor_code
     *
     * @param vendorCode the value for t_sync_erp.vendor_code
     *
     * @mbg.generated
     */
    public void setVendorCode(String vendorCode) {
        this.vendorCode = vendorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.vendor_rate
     *
     * @return the value of t_sync_erp.vendor_rate
     *
     * @mbg.generated
     */
    public BigDecimal getVendorRate() {
        return vendorRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.vendor_rate
     *
     * @param vendorRate the value for t_sync_erp.vendor_rate
     *
     * @mbg.generated
     */
    public void setVendorRate(BigDecimal vendorRate) {
        this.vendorRate = vendorRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.merchant_no
     *
     * @return the value of t_sync_erp.merchant_no
     *
     * @mbg.generated
     */
    public String getMerchantNo() {
        return merchantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.merchant_no
     *
     * @param merchantNo the value for t_sync_erp.merchant_no
     *
     * @mbg.generated
     */
    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.push_month
     *
     * @return the value of t_sync_erp.push_month
     *
     * @mbg.generated
     */
    public String getPushMonth() {
        return pushMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.push_month
     *
     * @param pushMonth the value for t_sync_erp.push_month
     *
     * @mbg.generated
     */
    public void setPushMonth(String pushMonth) {
        this.pushMonth = pushMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.audit_status
     *
     * @return the value of t_sync_erp.audit_status
     *
     * @mbg.generated
     */
    public Byte getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.audit_status
     *
     * @param auditStatus the value for t_sync_erp.audit_status
     *
     * @mbg.generated
     */
    public void setAuditStatus(Byte auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.erp_status
     *
     * @return the value of t_sync_erp.erp_status
     *
     * @mbg.generated
     */
    public Byte getErpStatus() {
        return erpStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.erp_status
     *
     * @param erpStatus the value for t_sync_erp.erp_status
     *
     * @mbg.generated
     */
    public void setErpStatus(Byte erpStatus) {
        this.erpStatus = erpStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.erp_error_message
     *
     * @return the value of t_sync_erp.erp_error_message
     *
     * @mbg.generated
     */
    public String getErpErrorMessage() {
        return erpErrorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.erp_error_message
     *
     * @param erpErrorMessage the value for t_sync_erp.erp_error_message
     *
     * @mbg.generated
     */
    public void setErpErrorMessage(String erpErrorMessage) {
        this.erpErrorMessage = erpErrorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.create_time
     *
     * @return the value of t_sync_erp.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.create_time
     *
     * @param createTime the value for t_sync_erp.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.update_time
     *
     * @return the value of t_sync_erp.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.update_time
     *
     * @param updateTime the value for t_sync_erp.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.pay_parent_channel
     *
     * @return the value of t_sync_erp.pay_parent_channel
     *
     * @mbg.generated
     */
    public Byte getPayParentChannel() {
        return payParentChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.pay_parent_channel
     *
     * @param payParentChannel the value for t_sync_erp.pay_parent_channel
     *
     * @mbg.generated
     */
    public void setPayParentChannel(Byte payParentChannel) {
        this.payParentChannel = payParentChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.erp_group_id
     *
     * @return the value of t_sync_erp.erp_group_id
     *
     * @mbg.generated
     */
    public String getErpGroupId() {
        return erpGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.erp_group_id
     *
     * @param erpGroupId the value for t_sync_erp.erp_group_id
     *
     * @mbg.generated
     */
    public void setErpGroupId(String erpGroupId) {
        this.erpGroupId = erpGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.journal_key
     *
     * @return the value of t_sync_erp.journal_key
     *
     * @mbg.generated
     */
    public String getJournalKey() {
        return journalKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.journal_key
     *
     * @param journalKey the value for t_sync_erp.journal_key
     *
     * @mbg.generated
     */
    public void setJournalKey(String journalKey) {
        this.journalKey = journalKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.member_benefit_price
     *
     * @return the value of t_sync_erp.member_benefit_price
     *
     * @mbg.generated
     */
    public BigDecimal getMemberBenefitPrice() {
        return memberBenefitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.member_benefit_price
     *
     * @param memberBenefitPrice the value for t_sync_erp.member_benefit_price
     *
     * @mbg.generated
     */
    public void setMemberBenefitPrice(BigDecimal memberBenefitPrice) {
        this.memberBenefitPrice = memberBenefitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.total_benefit_price
     *
     * @return the value of t_sync_erp.total_benefit_price
     *
     * @mbg.generated
     */
    public BigDecimal getTotalBenefitPrice() {
        return totalBenefitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.total_benefit_price
     *
     * @param totalBenefitPrice the value for t_sync_erp.total_benefit_price
     *
     * @mbg.generated
     */
    public void setTotalBenefitPrice(BigDecimal totalBenefitPrice) {
        this.totalBenefitPrice = totalBenefitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.push_erp_type
     *
     * @return the value of t_sync_erp.push_erp_type
     *
     * @mbg.generated
     */
    public Byte getPushErpType() {
        return pushErpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.push_erp_type
     *
     * @param pushErpType the value for t_sync_erp.push_erp_type
     *
     * @mbg.generated
     */
    public void setPushErpType(Byte pushErpType) {
        this.pushErpType = pushErpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_erp.businessId
     *
     * @return the value of t_sync_erp.businessId
     *
     * @mbg.generated
     */
    public Byte getBusinessid() {
        return businessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_erp.businessId
     *
     * @param businessid the value for t_sync_erp.businessId
     *
     * @mbg.generated
     */
    public void setBusinessid(Byte businessid) {
        this.businessid = businessid;
    }
}