package com.mjj.orm.mybatis.demo.mapper;

import com.mjj.orm.mybatis.demo.dto.TBenefitHadesErp;

public interface TBenefitHadesErpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_benefit_hades_erp
     *
     * @mbg.generated
     */
    int insert(TBenefitHadesErp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_benefit_hades_erp
     *
     * @mbg.generated
     */
    int insertSelective(TBenefitHadesErp record);
}