package com.mjj.orm.mybatis.demo.mapper;

import com.mjj.orm.mybatis.demo.dto.TCategoryAttributeItem;

public interface TCategoryAttributeItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_attribute_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_attribute_item
     *
     * @mbg.generated
     */
    int insert(TCategoryAttributeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_attribute_item
     *
     * @mbg.generated
     */
    int insertSelective(TCategoryAttributeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_attribute_item
     *
     * @mbg.generated
     */
    TCategoryAttributeItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_attribute_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCategoryAttributeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_attribute_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCategoryAttributeItem record);
}