package com.mjj.orm.mybatis.demo.mapper;

import com.mjj.orm.mybatis.demo.dto.TMmallOrderVendor;

public interface TMmallOrderVendorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order_vendor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order_vendor
     *
     * @mbg.generated
     */
    int insert(TMmallOrderVendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order_vendor
     *
     * @mbg.generated
     */
    int insertSelective(TMmallOrderVendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order_vendor
     *
     * @mbg.generated
     */
    TMmallOrderVendor selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order_vendor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMmallOrderVendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order_vendor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMmallOrderVendor record);
}