package com.mjj.orm.mybatis.demo.mapper;

import com.mjj.orm.mybatis.demo.dto.TMmallSubOrder;

public interface TMmallSubOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_sub_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_sub_order
     *
     * @mbg.generated
     */
    int insert(TMmallSubOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_sub_order
     *
     * @mbg.generated
     */
    int insertSelective(TMmallSubOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_sub_order
     *
     * @mbg.generated
     */
    TMmallSubOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_sub_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMmallSubOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_sub_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMmallSubOrder record);
}