package com.mjj.orm.mybatis.demo.mapper;

import com.mjj.orm.mybatis.demo.dto.TMmallOrderSuccessNotify;

public interface TMmallOrderSuccessNotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order_success_notify
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order_success_notify
     *
     * @mbg.generated
     */
    int insert(TMmallOrderSuccessNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order_success_notify
     *
     * @mbg.generated
     */
    int insertSelective(TMmallOrderSuccessNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order_success_notify
     *
     * @mbg.generated
     */
    TMmallOrderSuccessNotify selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order_success_notify
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMmallOrderSuccessNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order_success_notify
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TMmallOrderSuccessNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order_success_notify
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMmallOrderSuccessNotify record);
}