package com.mjj.orm.mybatis.demo.mapper;

import com.mjj.orm.mybatis.demo.dto.TMmallTencentVipLogBak20180727;

public interface TMmallTencentVipLogBak20180727Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_tencent_vip_log_bak_20180727
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_tencent_vip_log_bak_20180727
     *
     * @mbg.generated
     */
    int insert(TMmallTencentVipLogBak20180727 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_tencent_vip_log_bak_20180727
     *
     * @mbg.generated
     */
    int insertSelective(TMmallTencentVipLogBak20180727 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_tencent_vip_log_bak_20180727
     *
     * @mbg.generated
     */
    TMmallTencentVipLogBak20180727 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_tencent_vip_log_bak_20180727
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMmallTencentVipLogBak20180727 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_tencent_vip_log_bak_20180727
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMmallTencentVipLogBak20180727 record);
}