package com.mjj.orm.mybatis.demo.mapper;

import com.mjj.orm.mybatis.demo.dto.TMmallOrder;

public interface TMmallOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order
     *
     * @mbg.generated
     */
    int insert(TMmallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order
     *
     * @mbg.generated
     */
    int insertSelective(TMmallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order
     *
     * @mbg.generated
     */
    TMmallOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMmallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TMmallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMmallOrder record);
}