package com.mjj.orm.mybatis.demo.mapper;

import com.mjj.orm.mybatis.demo.dto.TMmallTencentVip;

public interface TMmallTencentVipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_tencent_vip
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_tencent_vip
     *
     * @mbg.generated
     */
    int insert(TMmallTencentVip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_tencent_vip
     *
     * @mbg.generated
     */
    int insertSelective(TMmallTencentVip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_tencent_vip
     *
     * @mbg.generated
     */
    TMmallTencentVip selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_tencent_vip
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMmallTencentVip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_tencent_vip
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMmallTencentVip record);
}