package com.mjj.orm.mybatis.demo.mapper;

import com.mjj.orm.mybatis.demo.dto.TMmallVip;

public interface TMmallVipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_vip
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_vip
     *
     * @mbg.generated
     */
    int insert(TMmallVip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_vip
     *
     * @mbg.generated
     */
    int insertSelective(TMmallVip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_vip
     *
     * @mbg.generated
     */
    TMmallVip selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_vip
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMmallVip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_vip
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMmallVip record);
}