package com.mjj.orm.mybatis.demo.mapper;

import com.mjj.orm.mybatis.demo.dto.TMmallOrderRefund;

public interface TMmallOrderRefundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order_refund
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order_refund
     *
     * @mbg.generated
     */
    int insert(TMmallOrderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order_refund
     *
     * @mbg.generated
     */
    int insertSelective(TMmallOrderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order_refund
     *
     * @mbg.generated
     */
    TMmallOrderRefund selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMmallOrderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TMmallOrderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mmall_order_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMmallOrderRefund record);
}