package com.mjj.orm.mybatis.demo.mapper;

import com.mjj.orm.mybatis.demo.dto.TOperationMerchant;

public interface TOperationMerchantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_merchant
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_merchant
     *
     * @mbg.generated
     */
    int insert(TOperationMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_merchant
     *
     * @mbg.generated
     */
    int insertSelective(TOperationMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_merchant
     *
     * @mbg.generated
     */
    TOperationMerchant selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_merchant
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TOperationMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_merchant
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TOperationMerchant record);
}