package com.mjj.orm.mybatis.demo.mapper;

import com.mjj.orm.mybatis.demo.dto.TOperationProduct;

public interface TOperationProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_product
     *
     * @mbg.generated
     */
    int insert(TOperationProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_product
     *
     * @mbg.generated
     */
    int insertSelective(TOperationProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_product
     *
     * @mbg.generated
     */
    TOperationProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TOperationProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TOperationProduct record);
}