package com.mjj.orm.mybatis.demo.mapper;

import com.mjj.orm.mybatis.demo.dto.TOperationRefund;

public interface TOperationRefundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_refund
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_refund
     *
     * @mbg.generated
     */
    int insert(TOperationRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_refund
     *
     * @mbg.generated
     */
    int insertSelective(TOperationRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_refund
     *
     * @mbg.generated
     */
    TOperationRefund selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TOperationRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TOperationRefund record);
}