package com.mjj.orm.mybatis.demo.mapper;

import com.mjj.orm.mybatis.demo.dto.TOperationPushErp;
import org.apache.ibatis.annotations.Param;

public interface TOperationPushErpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_push_erp
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("type") Integer type, @Param("auditDate") String auditDate, @Param("payParentChannel") Byte payParentChannel, @Param("vendorCode") String vendorCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_push_erp
     *
     * @mbg.generated
     */
    int insert(TOperationPushErp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_push_erp
     *
     * @mbg.generated
     */
    int insertSelective(TOperationPushErp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_push_erp
     *
     * @mbg.generated
     */
    TOperationPushErp selectByPrimaryKey(@Param("type") Integer type, @Param("auditDate") String auditDate, @Param("payParentChannel") Byte payParentChannel, @Param("vendorCode") String vendorCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_push_erp
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TOperationPushErp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_push_erp
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TOperationPushErp record);
}