package com.mjj.orm.mybatis.demo.mapper;

import com.mjj.orm.mybatis.demo.dto.TSku;

public interface TSkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku
     *
     * @mbg.generated
     */
    int insert(TSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku
     *
     * @mbg.generated
     */
    int insertSelective(TSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku
     *
     * @mbg.generated
     */
    TSku selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSku record);
}