package com.mjj.orm.mybatis.demo.mapper;

import com.mjj.orm.mybatis.demo.dto.TSkuSaleAttributeItem;

public interface TSkuSaleAttributeItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku_sale_attribute_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku_sale_attribute_item
     *
     * @mbg.generated
     */
    int insert(TSkuSaleAttributeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku_sale_attribute_item
     *
     * @mbg.generated
     */
    int insertSelective(TSkuSaleAttributeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku_sale_attribute_item
     *
     * @mbg.generated
     */
    TSkuSaleAttributeItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku_sale_attribute_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSkuSaleAttributeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku_sale_attribute_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSkuSaleAttributeItem record);
}