package com.mjj.orm.mybatis.demo.mapper;

import com.mjj.orm.mybatis.demo.dto.TSpuActivity;

public interface TSpuActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spu_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spu_activity
     *
     * @mbg.generated
     */
    int insert(TSpuActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spu_activity
     *
     * @mbg.generated
     */
    int insertSelective(TSpuActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spu_activity
     *
     * @mbg.generated
     */
    TSpuActivity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spu_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSpuActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spu_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSpuActivity record);
}