package com.mjj.orm.mybatis.demo.mapper;

import com.mjj.orm.mybatis.demo.dto.TSyncBenefitOrder;

public interface TSyncBenefitOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sync_benefit_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sync_benefit_order
     *
     * @mbg.generated
     */
    int insert(TSyncBenefitOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sync_benefit_order
     *
     * @mbg.generated
     */
    int insertSelective(TSyncBenefitOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sync_benefit_order
     *
     * @mbg.generated
     */
    TSyncBenefitOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sync_benefit_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSyncBenefitOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sync_benefit_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSyncBenefitOrder record);
}