package com.mjj.orm.mybatis.demo.mapper;

import com.mjj.orm.mybatis.demo.dto.TVendor;

public interface TVendorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vendor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vendor
     *
     * @mbg.generated
     */
    int insert(TVendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vendor
     *
     * @mbg.generated
     */
    int insertSelective(TVendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vendor
     *
     * @mbg.generated
     */
    TVendor selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vendor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TVendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vendor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TVendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vendor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TVendor record);
}